/*
 * ################################################################
 *
 * ProActive: The Java(TM) library for Parallel, Distributed,
 *            Concurrent computing with Security and Mobility
 *
 * Copyright (C) 1997-2007 INRIA/University of Nice-Sophia Antipolis
 * Contact: proactive@objectweb.org
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version
 * 2 of the License, or any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307
 * USA
 *
 *  Initial developer(s):               The ProActive Team
 *                        http://proactive.inria.fr/team_members.htm
 *  Contributor(s):
 *
 * ################################################################
 */
package org.objectweb.proactive.extensions.resourcemanager.frontend;

import java.util.ArrayList;
import java.util.HashMap;

import org.objectweb.proactive.annotation.PublicAPI;
import org.objectweb.proactive.core.descriptor.data.ProActiveDescriptor;
import org.objectweb.proactive.core.descriptor.data.VirtualNode;
import org.objectweb.proactive.core.util.wrapper.IntWrapper;
import org.objectweb.proactive.core.util.wrapper.StringWrapper;
import org.objectweb.proactive.extensions.resourcemanager.common.event.RMEventType;
import org.objectweb.proactive.extensions.resourcemanager.common.event.RMInitialState;
import org.objectweb.proactive.extensions.resourcemanager.rmnode.RMNode;


/**
 * An interface Front-End for the Monitoring of the Resource Manager.
 * This interface provides a way for a monitor to ask at
 * Resource Manager to throw events
 * generated by nodes and nodes sources management.
 *
 *        //TODO methods to add and remove because RM GUI is in development,
 *        so Java Doc not yet up to date for this component
 *
 *        @see org.objectweb.proactive.extensions.resourcemanager.frontend.RMEventListener
 *
 * * @author ProActive team.
 */
@PublicAPI
public interface RMMonitoring {

    /** Echo function */
    public StringWrapper echo();

    /**
     * Gives all deployed ProActive descriptors.
     * Get the virtual nodes for redeploying or killing nodes.<BR/>
     * For getting the virtual nodes of a pad call this method :<BR/>
     * VirtualNode[] vnodes = pad.getVirtualNodes();
     * @return hashmap < String padName, ProActiveDescriptor pad >
     *
     *         TODO gsigety remove this method when new RM GUI will be available
     */
    public HashMap<String, ProActiveDescriptor> getListDescriptor();

    /**
     * This method serve to get all deployed virtualnodes by proactive descriptor.
     * @return hashmap < String padName, ArrayList<VirtualNode> list of deployed virtualnodes >
     *
     *         TODO gsigety remove this method when new RM GUI will be available
     */
    public HashMap<String, ArrayList<VirtualNode>> getDeployedVirtualNodeByPad();

    /**
     * @return the ArrayList of RMNode know by the RM, it's a set of
     *  free RMNodes and busy RMNodes.
     *  @see RMNode
     *
     *         TODO gsigety remove this method when new RM GUI will be available
     */
    public ArrayList<RMNode> getListAllIMNodes();

    /**
     * @return the ArrayList of free Node
     *
     *         TODO gsigety remove this method when new RM GUI will be available
     *
     * @see RMNode
     */
    public ArrayList<RMNode> getListFreeIMNode();

    /**
     *
     *         TODO gsigety remove this method when new RM GUI will be available
     *
     * @return the ArrayList of used Node
     * @see RMNode
     */
    public ArrayList<RMNode> getListBusyIMNode();

    /**
     *
     *         TODO gsigety remove this method when new RM GUI will be available
     *
     * @return the number of free resource RMNode
     */
    public IntWrapper getNumberOfFreeResource();

    /**
     *
     *         TODO gsigety remove this method when new RM GUI will be available
     *
     * @return the number of used resource RMNode
     */
    public IntWrapper getNumberOfBusyResource();

    /**
     *
     *         TODO gsigety remove this method when new RM GUI will be available
     *
     * @return the number of down resource RMNode
     */
    public IntWrapper getNumberOfDownResource();

    /**
     *
     *         TODO gsigety remove this method when new RM GUI will be available
     *
     * @return the number of all resource RMNode
     */
    public IntWrapper getNumberOfAllResources();

    /** Register a new Resource manager listener.
     * Way to a monitor object to ask at RMMonitoring to throw
     * RM events to it.
     * @param listener a listener object which implements {@link RMEventListener}
     * interface.
     * @param events list of wanted events that must be received.
     * @return RMInitialState snapshot of RM's current state : nodes and node sources.
     *  */
    public RMInitialState addRMEventListener(RMEventListener listener,
        RMEventType... events);

    /** Stop and remove monitoring active object */
    public void shutdown();
}
