/*
 * ################################################################
 *
 * ProActive Parallel Suite(TM): The Java(TM) library for
 *    Parallel, Distributed, Multi-Core Computing for
 *    Enterprise Grids & Clouds
 *
 * Copyright (C) 1997-2010 INRIA/University of 
 * 				Nice-Sophia Antipolis/ActiveEon
 * Contact: proactive@ow2.org or contact@activeeon.com
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; version 3 of
 * the License.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307
 * USA
 *
 * If needed, contact us to obtain a release under GPL Version 2 
 * or a different license than the GPL.
 *
 *  Initial developer(s):               The ProActive Team
 *                        http://proactive.inria.fr/team_members.htm
 *  Contributor(s):
 *
 * ################################################################
 * $$PROACTIVE_INITIAL_DEV$$
 */
package org.ow2.proactive.resourcemanager.common.event;

import org.objectweb.proactive.annotation.PublicAPI;


/**
 * Enumeration of all events generated by the Resource Manager,
 * and received by Monitors, which permit to probe RM activity.
 *
 * @see org.ow2.proactive.resourcemanager.frontend.RMMonitoring
 *
 * @author The ProActive Team
 * @since ProActive Scheduling 0.9
 *
 */
@PublicAPI
public enum RMEventType {
    /**
     * Resource manager has been shutdown
     */
    SHUTDOWN,
    /**
     * Resource manager cessation as been asked, so Resource manager performs 
     * shutting down operations.  
     */
    SHUTTING_DOWN,
    /**
     * Resource manager has been launched. 
     */
    STARTED,
    /**
     * A new node source has been created in Resource manager.
     */
    NODESOURCE_CREATED,
    /**
     * A node source has been removed removed from resource manager.
     */
    NODESOURCE_REMOVED,
    /**
     * A new node has been added to Resource manager, and is ready to
     * be provided to a RM user.
     */
    NODE_ADDED,
    /**
     * Node state has been changes 
     */
    NODE_STATE_CHANGED,
    /**
     * A node has been removed from Resource manager
     */
    NODE_REMOVED,

    /**
     * The resource manager is alive
     */
    ALIVE;
}
