#!/bin/bash -p
(
# Un path minimal de precaution. Evite automounts superflus.
# \\ Voir si ca gene java. Ca devrait pas
export PATH=/bin:/usr/bin:/usr/local/bin

# Logfile date'
log=/tmp/oasisgrid/log

dlog=$log-$(date '+%m%d%H%M%S')
# Pour acces simple au log courant, on le linke non date'
ln -sf ${dlog##*/} $log

# Pour que tout le groupe oasis ait acces en ecriture
umask 002

exec > $dlog 2>&1

echo "$0 $@: start: $(date)"

idle=$(vmstat 30 2)
idle=${idle##* }

((idle<80)) && {
    echo >&2 "Trop de charge ($idle): Abandon"
    exit 1
}

