/*
 * ################################################################
 *
 * ProActive: The Java(TM) library for Parallel, Distributed,
 *            Concurrent computing with Security and Mobility
 *
 * Copyright (C) 1997-2007 INRIA/University of Nice-Sophia Antipolis
 * Contact: proactive@objectweb.org
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version
 * 2 of the License, or any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307
 * USA
 *
 *  Initial developer(s):               The ProActive Team
 *                        http://proactive.inria.fr/team_members.htm
 *  Contributor(s):
 *
 * ################################################################
 */
package trywithcatch;

//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Fri Sep 23 17:08:31 CEST 2005
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
    /* terminals */
    public static final int REMOVE_TRY_WITH_CATCH = 10;
    public static final int CATCH = 4;
    public static final int IDENT = 2;
    public static final int TRY_WITH_CATCH = 8;
    public static final int EOF = 0;
    public static final int error = 1;
    public static final int FINALLY = 5;
    public static final int BLOCK_END = 7;
    public static final int TRY = 3;
    public static final int BLOCK_START = 6;
    public static final int END_TRY_WITH_CATCH = 9;
}
