/*
 * ################################################################
 *
 * ProActive: The Java(TM) library for Parallel, Distributed,
 *            Concurrent computing with Security and Mobility
 *
 * Copyright (C) 1997-2007 INRIA/University of Nice-Sophia Antipolis
 * Contact: proactive@objectweb.org
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version
 * 2 of the License, or any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307
 * USA
 *
 *  Initial developer(s):               The ProActive Team
 *                        http://proactive.inria.fr/team_members.htm
 *  Contributor(s):
 *
 * ################################################################
 */
package org.objectweb.proactive.extra.infrastructuremanager.frontend;

import java.util.ArrayList;
import java.util.HashMap;

import org.objectweb.proactive.annotation.PublicAPI;
import org.objectweb.proactive.core.descriptor.data.ProActiveDescriptor;
import org.objectweb.proactive.core.descriptor.data.VirtualNode;
import org.objectweb.proactive.core.util.wrapper.IntWrapper;
import org.objectweb.proactive.core.util.wrapper.StringWrapper;
import org.objectweb.proactive.extra.infrastructuremanager.common.IMEvent;
import org.objectweb.proactive.extra.infrastructuremanager.common.IMInitialState;
import org.objectweb.proactive.extra.infrastructuremanager.imnode.IMNode;


/**
 * An interface Front-End for the Monitoring of the Infrastructure Manager.
 * This interface provides a way for a monitor to ask at
 * Infrastructure Manager to throw events
 * generated by nodes and nodes sources management.
 *
 *        //TODO methods to add and remove because IM GUI is in development,
 *        so Java Doc not yet up to date for this component
 *
 *        @see org.objectweb.proactive.extra.infrastructuremanager.frontend.IMEventListener
 *
 * * @author ProActive team.
 */
@PublicAPI
public interface IMMonitoring {

    /** Echo function */
    public StringWrapper echo();

    /**
     * Gives all deployed ProActive descriptors.
     * Get the virtual nodes for redeploying or killing nodes.<BR/>
     * For getting the virtual nodes of a pad call this method :<BR/>
     * VirtualNode[] vnodes = pad.getVirtualNodes();
     * @return hashmap < String padName, ProActiveDescriptor pad >
     *
     *         TODO gsigety remove this method when new IM GUI will be available
     */
    public HashMap<String, ProActiveDescriptor> getListDescriptor();

    /**
     * This method serve to get all deployed virtualnodes by proactive descriptor.
     * @return hashmap < String padName, ArrayList<VirtualNode> list of deployed virtualnodes >
     *
     *         TODO gsigety remove this method when new IM GUI will be available
     */
    public HashMap<String, ArrayList<VirtualNode>> getDeployedVirtualNodeByPad();

    /**
     * @return the ArrayList of IMNode know by the IM, it's a set of
     *  free IMNodes and busy IMNodes.
     *  @see IMNode
     *
     *         TODO gsigety remove this method when new IM GUI will be available
     */
    public ArrayList<IMNode> getListAllIMNodes();

    /**
     * @return the ArrayList of free Node
     *
     *         TODO gsigety remove this method when new IM GUI will be available
     *
     * @see IMNode
     */
    public ArrayList<IMNode> getListFreeIMNode();

    /**
     *
     *         TODO gsigety remove this method when new IM GUI will be available
     *
     * @return the ArrayList of used Node
     * @see IMNode
     */
    public ArrayList<IMNode> getListBusyIMNode();

    /**
     *
     *         TODO gsigety remove this method when new IM GUI will be available
     *
     * @return the number of free resource IMNode
     */
    public IntWrapper getNumberOfFreeResource();

    /**
     *
     *         TODO gsigety remove this method when new IM GUI will be available
     *
     * @return the number of used resource IMNode
     */
    public IntWrapper getNumberOfBusyResource();

    /**
     *
     *         TODO gsigety remove this method when new IM GUI will be available
     *
     * @return the number of down resource IMNode
     */
    public IntWrapper getNumberOfDownResource();

    /**
     *
     *         TODO gsigety remove this method when new IM GUI will be available
     *
     * @return the number of all resource IMNode
     */
    public IntWrapper getNumberOfAllResources();

    /** Register a new Infrastructure manager listener.
     * Way to a monitor object to ask at IMMonitoring to throw
     * IM events to it.
     * @param listener a listener object which implements {@link IMEventListener}
     * interface.
     * @param events list of wanted events that must be received.
     * @return IMInitialState snapshot of IM's current state : nodes and node sources.
     *  */
    public IMInitialState addIMEventListener(IMEventListener listener,
        IMEvent... events);
}
