/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class util_timer_MicroTimer */

#ifndef _Included_util_timer_MicroTimer
#define _Included_util_timer_MicroTimer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     util_timer_MicroTimer
 * Method:    currentTime
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_util_timer_MicroTimer_currentTime
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
