#!/bin/bash
#
# Start a ProActive Runtime through ssh to the host and register it in the Resource Manager.
# Script will be killed when the node is registered.
#

# Script parameters
HOST_NAME=$1
NODE_NAME=$2
NODE_SOURCE_NAME=$3
RM_URL=$4

# Script constants
RM_HOME_NODE="UPDATE_ME"
JAVA_HOME_NODE="UPDATE_ME"
JAVA_OPTS_NODE="-Djava.security.policy=$RM_HOME_NODE/config/security.java.policy-client"
CREDENTIALS="UPDATE_ME"

CLASSPATH="-cp .:"
CLASSPATH=$CLASSPATH:$RM_HOME_NODE/dist/lib/script-js.jar
CLASSPATH=$CLASSPATH:$RM_HOME_NODE/dist/lib/jruby-engine.jar
CLASSPATH=$CLASSPATH:$RM_HOME_NODE/dist/lib/jython-engine.jar
CLASSPATH=$CLASSPATH:$RM_HOME_NODE/dist/lib/commons-logging-1.1.1.jar
CLASSPATH=$CLASSPATH:$RM_HOME_NODE/dist/lib/ProActive_SRM-common.jar
CLASSPATH=$CLASSPATH:$RM_HOME_NODE/dist/lib/ProActive_ResourceManager.jar
CLASSPATH=$CLASSPATH:$RM_HOME_NODE/dist/lib/ProActive_Scheduler-worker.jar
CLASSPATH=$CLASSPATH:$RM_HOME_NODE/dist/lib/ProActive_Scheduler-matsci.jar
CLASSPATH=$CLASSPATH:$RM_HOME_NODE/dist/lib/commons-httpclient-3.1.jar
CLASSPATH=$CLASSPATH:$RM_HOME_NODE/dist/lib/commons-codec-1.3.jar
CLASSPATH=$CLASSPATH:$RM_HOME_NODE/dist/lib/ProActive.jar
CLASSPATH=$CLASSPATH:$RM_HOME_NODE/addons

ssh $HOST_NAME nohup $JAVA_HOME_NODE/bin/java $JAVA_OPTS_NODE $CLASSPATH org.ow2.proactive.resourcemanager.utils.RMNodeStarter -v $CREDENTIALS -n $NODE_NAME -s $NODE_SOURCE_NAME -p 30000 -r $RM_URL &
SSH_PID=$!
trap "kill $SSH_PID" TERM

# waiting until the process is killed
wait $SSH_PID
