#!/bin/bash
#
# Start a ProActive node using java web start.
# It keep the version node up up date and remove the necessity to install anything on the node side.
#

# Script parameters
HOST_NAME=$1
NODE_NAME=$2
NODE_SOURCE_NAME=$3
RM_URL=$4

ssh $HOST_NAME nohup $JAVA_HOME_NODE/bin/javaws  http://localhost:8080/rest/rm/node.jnlp &
SSH_PID=$!
trap "kill $SSH_PID" TERM

# waiting until the process is killed
wait $SSH_PID
