/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class testsuite_imer_micro_MicroTimer */

#ifndef _Included_testsuite_timer_micro_MicroTimer
#define _Included_testsuite_timer_micro_MicroTimer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     testsuite_timer_micro_MicroTimer
 * Method:    currentTime
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_org_objectweb_proactive_core_util_timer_MicroTimer_currentTime
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
