#!/bin/bash -p

# pidof(1) may be in /sbin
PATH="$PATH:/sbin"

#set -o xtrace

for PID in $(pidof java); do
	grep -- "-Dproactive.test=true" /proc/$PID/cmdline    &&
	kill -9 $PID 2>/dev/null
done

killall -9 rmid rmiregistry
