/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __ptolemy_matlab_Engine__
#define __ptolemy_matlab_Engine__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jlong JNICALL Java_ptolemy_matlab_Engine_ptmatlabEngOpen (JNIEnv *env, jobject, jstring);
JNIEXPORT jint JNICALL Java_ptolemy_matlab_Engine_ptmatlabEngClose (JNIEnv *env, jobject, jlong, jlong);
JNIEXPORT jint JNICALL Java_ptolemy_matlab_Engine_ptmatlabEngEvalString (JNIEnv *env, jobject, jlong, jstring);
JNIEXPORT jlong JNICALL Java_ptolemy_matlab_Engine_ptmatlabEngGetArray (JNIEnv *env, jobject, jlong, jstring);
JNIEXPORT jint JNICALL Java_ptolemy_matlab_Engine_ptmatlabEngPutArray (JNIEnv *env, jobject, jlong, jstring, jlong);
JNIEXPORT jlong JNICALL Java_ptolemy_matlab_Engine_ptmatlabEngOutputBuffer (JNIEnv *env, jobject, jlong, jint);
JNIEXPORT jlong JNICALL Java_ptolemy_matlab_Engine_ptmatlabCreateCellMatrix (JNIEnv *env, jobject, jstring, jint, jint);
JNIEXPORT jlong JNICALL Java_ptolemy_matlab_Engine_ptmatlabCreateString (JNIEnv *env, jobject, jstring, jstring, jint, jint);
JNIEXPORT jlong JNICALL Java_ptolemy_matlab_Engine_ptmatlabCreateDoubleMatrixOneDim (JNIEnv *env, jobject, jstring, jdoubleArray, jint);
JNIEXPORT jlong JNICALL Java_ptolemy_matlab_Engine_ptmatlabCreateDoubleMatrix (JNIEnv *env, jobject, jstring, jobjectArray, jint, jint);
JNIEXPORT jlong JNICALL Java_ptolemy_matlab_Engine_ptmatlabCreateComplexMatrixOneDim (JNIEnv *env, jobject, jstring, jobjectArray, jint);
JNIEXPORT jlong JNICALL Java_ptolemy_matlab_Engine_ptmatlabCreateComplexMatrix (JNIEnv *env, jobject, jstring, jobjectArray, jint, jint);
JNIEXPORT jlong JNICALL Java_ptolemy_matlab_Engine_ptmatlabCreateStructMatrix (JNIEnv *env, jobject, jstring, jobjectArray, jint, jint);
JNIEXPORT void JNICALL Java_ptolemy_matlab_Engine_ptmatlabDestroy (JNIEnv *env, jobject, jlong, jstring);
JNIEXPORT jlong JNICALL Java_ptolemy_matlab_Engine_ptmatlabGetCell (JNIEnv *env, jobject, jlong, jint, jint);
JNIEXPORT jstring JNICALL Java_ptolemy_matlab_Engine_ptmatlabGetClassName (JNIEnv *env, jobject, jlong);
JNIEXPORT jintArray JNICALL Java_ptolemy_matlab_Engine_ptmatlabGetDimensions (JNIEnv *env, jobject, jlong);
JNIEXPORT jobjectArray JNICALL Java_ptolemy_matlab_Engine_ptmatlabGetComplexMatrix (JNIEnv *env, jobject, jlong, jint, jint);
JNIEXPORT jobjectArray JNICALL Java_ptolemy_matlab_Engine_ptmatlabGetDoubleMatrix (JNIEnv *env, jobject, jlong, jint, jint);
JNIEXPORT jobjectArray JNICALL Java_ptolemy_matlab_Engine_ptmatlabGetLogicalMatrix (JNIEnv *env, jobject, jlong, jint, jint);
JNIEXPORT jstring JNICALL Java_ptolemy_matlab_Engine_ptmatlabGetFieldNameByNumber (JNIEnv *env, jobject, jlong, jint);
JNIEXPORT jlong JNICALL Java_ptolemy_matlab_Engine_ptmatlabGetFieldByNumber (JNIEnv *env, jobject, jlong, jint, jint, jint);
JNIEXPORT jint JNICALL Java_ptolemy_matlab_Engine_ptmatlabGetNumberOfFields (JNIEnv *env, jobject, jlong);
JNIEXPORT jstring JNICALL Java_ptolemy_matlab_Engine_ptmatlabGetString (JNIEnv *env, jobject, jlong, jint);
JNIEXPORT jstring JNICALL Java_ptolemy_matlab_Engine_ptmatlabGetOutput (JNIEnv *env, jobject, jlong, jint);
JNIEXPORT jboolean JNICALL Java_ptolemy_matlab_Engine_ptmatlabIsComplex (JNIEnv *env, jobject, jlong);
JNIEXPORT void JNICALL Java_ptolemy_matlab_Engine_ptmatlabSetCell (JNIEnv *env, jobject, jstring, jlong, jint, jint, jlong);
JNIEXPORT void JNICALL Java_ptolemy_matlab_Engine_ptmatlabSetString (JNIEnv *env, jobject, jstring, jlong, jint, jstring, jint);
JNIEXPORT void JNICALL Java_ptolemy_matlab_Engine_ptmatlabSetStructField (JNIEnv *env, jobject, jstring, jlong, jstring, jint, jint, jlong);

#ifdef __cplusplus
}
#endif

#endif /* __ptolemy_matlab_Engine__ */
