#! /bin/bash

source $(dirname $0)/g5k_lib.sh

CLUSTER=orsay
if [ $# -gt 0 ] ; then
	NODES=$*
else 
	NODES=$(`dirname $0`/g5k_reservedNodes -s $CLUSTER)
fi
KADEPLOY_ARGS="-e debian4all -p sda3 -l deploy "
MOUNT_ARGS="nfs.orsay.grid5000.fr:/home/sophia /home/sophia"

. $(dirname $0)/deploy/deploy
