#! /bin/sh

source $(dirname $0)/g5k_lib.sh

function print_help {
	echo -e "Usage: $0 [-a|-o|-s cluster]"
	echo -e "Deploy a debian4jul image on given sites\n"
	modopt_print_help
	exit 1
}

ARGS="h"

modopt_parse $ARGS $*
while getopts "${MODOPT_OPTS}${ARGS}" Option
do
	case $Option in
	h) print_help ;;
	*)
		modopt_error_handle $Option
		if [ "$?" -eq 0 ] ; then
			echo -e "Invalid option: $Option" 1>&2
			print_help
			exit 1
		fi
	;;
	esac
done

SSH=$(dirname $0)/deploy/ssh_autologin.exp

for i in `seq 0 $((${#OPTIONS_CLUSTERS[@]}-1))` ; 
do
	CLUSTER=${OPTIONS_CLUSTERS[$i]}
	NODES=$(`dirname $0`/g5k_reservedNodes -s $CLUSTER)
	KADEPLOY_ARGS="-l jleduc -e debian4jul -p $(get_kadeploy_part $CLUSTER)"

	for j in $NODES ; do KADEPLOY_ARGS="$KADEPLOY_ARGS -m $j " ; done
	ssh $(get_oar_hostname $CLUSTER) kadeploy $KADEPLOY_ARGS &

done

while true ; do
	if [ "$(ps aux | grep $USER | grep kadeploy|grep -v grep)" = "" ] ; then break ; fi
	sleep 15
done

for i in `seq 0 $((${#OPTIONS_CLUSTERS[@]}-1))` ; 
do
	CLUSTER=${OPTIONS_CLUSTERS[$i]}
	NODES=$(`dirname $0`/g5k_reservedNodes -s $CLUSTER)
	
	for j in $NODES ; 
	do 
		# WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!
		# PLEASE SHUT UP !
		#sed -i "s/^$j.*//"  ~/.ssh/known_hosts
		rm  ~/.ssh/known_hosts

		$SSH $ROOT_PASSWD $j groupadd  -g `id -g` sophia 
		$SSH $ROOT_PASSWD $j useradd -d $HOME -g `id -g` -p grid5000 -u `id -u` $USER
	done
done

