#! /bin/bash

source $(dirname $0)/g5k_lib.sh

CLUSTER=azur.sophia
NODES=$(`dirname $0`/g5k_reservedNodes -s $CLUSTER)
KADEPLOY_ARGS="-e fedora4all -p hda6 -l deploy "
MOUNT_ARGS="nfs.sophia.grid5000.fr:/export/home /home"

. $(dirname $0)/deploy/deploy
