#! /bin/bash

source $(dirname $0)/g5k_lib.sh

CLUSTER=bordeaux
if [ $# -gt 0 ] ; then
	NODES=$*
else 
	NODES=$(`dirname $0`/g5k_reservedNodes -s $CLUSTER)
fi
KADEPLOY_ARGS="-e fedora4all -p hda3 -l deploy "
MOUNT_ARGS="nfs.bordeaux.grid5000.fr:/home/local /home"

. $(dirname $0)/deploy/deploy
