#! /bin/bash

source $(dirname $0)/g5k_lib.sh

CLUSTER=paravent.rennes
NODES=$(`dirname $0`/g5k_reservedNodes -s $CLUSTER )
KADEPLOY_ARGS="-e fedora4all -p sda2 -l root "
MOUNT_ARGS="nfs-grid5000:/srv/home /home"

. $(dirname $0)/deploy/deploy
