#! /bin/sh

source $(dirname $0)/g5k_lib.sh

function print_help {
	echo -e "Usage: $0 [-f] [-j] [-a|-o|-c cluster]"
	echo -e "Print statistics about nodes and OAR Jobs\n"
	echo -e "\t-f       , print full node statistics"
	echo -e "\t-j       , print informations about OAR Jobs"
	modopt_print_help
	exit 1
}

ARGS="jfh"
OPT_J=No
OPT_F=No

modopt_parse $ARGS $*
while getopts "${MODOPT_OPTS}${ARGS}" Option
do
	case $Option in
  j) OPT_J=Yes ;;
	f) OPT_F=Yes ;;
	h) print_help ;;
	*)
		modopt_error_handle $Option
		if [ "$?" -eq 0 ] ; then
			echo -e "Invalid option: $Option" 1>&2
			print_help
			exit 1
		fi
	;;
	esac
done


if [ "$OPT_F" == "Yes" ] ;
then
	echo "-> Full OAR Statistics"
else
	echo "-> Free Nodes"
fi

for i in `seq 0 $((${#OPTIONS_CLUSTERS[@]}-1))` ; 
do
	CLUSTER=${OPTIONS_CLUSTERS[$i]}

	if [ "$OPT_F" == "Yes" ] ;
	then
		# Full statistics
		echo " $CLUSTER"
  	echo " $(get_nodesstats $CLUSTER)"
	else
		# Only free nodes
		echo -e " $CLUSTER\t\t: $(get_freenodes $CLUSTER)"
	fi
done

if [ "$OPT_J" == "Yes" ] ;
then
	echo -e "\n-> OAR Jobs:"
	for i in `seq 0 $((${#OPTIONS_CLUSTERS[@]}-1))` ; 
	do
		CLUSTER=${OPTIONS_CLUSTERS[$i]}
  	echo -e "$CLUSTER \n$(get_oar_jobs $CLUSTER)"
	done
fi

