#! /bin/sh

function print_help {
	echo "USAGE: $0" 
	echo -e "\t-j jobId , only this jobId"
	exit 1
}

function listNodes {
	jobId=$1
	if [ $(oarstat -f -j $jobId | egrep -c "(job_state = R|reservation = Scheduled)") == "2" ] ;
	then
		oarstat -f -j $jobId | grep exec_host | cut -d'=' -f2 | sed 's/+/ /g'
	fi
}

OPT_J=NO
JOBID=0

while getopts "hj:" Option
do
	case $Option in
	j )
		OPT_J=YES
		JOBID=$OPTARG
	;;	
	h ) 
		print_help       
	;;
	* ) 
		print_help       
	;;
	esac
done

if [ $OPT_J == "YES" ] ; 
then
	listNodes $JOBID
else 
	for res in $(oarstat | grep " $USER" | cut -d' ' -f1) ;
	do
		listNodes $res
	done
fi