/*
 * ################################################################
 *
 * ProActive: The Java(TM) library for Parallel, Distributed,
 *            Concurrent computing with Security and Mobility
 *
 * Copyright (C) 1997-2008 INRIA/University of Nice-Sophia Antipolis
 * Contact: proactive@ow2.org
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version
 * 2 of the License, or any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307
 * USA
 *
 *  Initial developer(s):               The ProActive Team
 *                        http://proactive.inria.fr/team_members.htm
 *  Contributor(s):
 *
 * ################################################################
 * $$PROACTIVE_INITIAL_DEV$$
 */
package org.ow2.proactive.scheduler.common.exception;

import org.objectweb.proactive.annotation.PublicAPI;


/**
 * Exceptions Generated by the scheduler due to a user problem.<br>
 * This exception is sent if an exception occurs and the problem comes from the user.
 *
 * @author The ProActive Team
 * @since ProActive Scheduling 0.9
 */
@PublicAPI
public class UserException extends Exception {

    /**
     *
     */
    private static final long serialVersionUID = 10L;

    /**
     * Attaches a message to the Exception.
     *
     * @param msg message attached.
     */
    public UserException(String msg) {
        super(msg);
    }

    /**
     * Create a new instance of UserException.
     */
    public UserException() {
        super();
    }

    /**
     * Create a new instance of UserException with the given message and cause
     *
     * @param msg the message to attach.
     * @param cause the cause of the exception.
     */
    public UserException(String msg, Throwable cause) {
        super(msg, cause);
    }

    /**
     * Create a new instance of UserException with the given cause.
     *
     * @param cause the cause of the exception.
     */
    public UserException(Throwable cause) {
        super(cause);
    }
}
