#!/bin/bash
#
# Start a ProActive Runtime through ssh to the host and register it in the Resource Manager.
# Script will be killed when the node is registered.
#

#
# This is a script template which is dynamically modified during test execution: strings 
# starting with '@' are substituted with appropriate values
#

# Script parameters
HOST_NAME=$1
NODE_NAME=$2
NODE_SOURCE_NAME=$3
RM_URL=$4

# Script constants
RM_HOME_NODE="@RM_HOME_NODE"
JAVA_PATH_NODE="@JAVA_PATH_NODE"
JAVA_OPTS_NODE="@NODE_JAVA_OPTS -Dproactive.node.reconnection.attempts=1 -Djava.security.policy=$RM_HOME_NODE/config/security.java.policy-client -Dpa.rm.home=$RM_HOME_NODE -Dproactive.home=$RM_HOME_NODE"
CREDENTIALS="@CREDENTIALS"

CLASSPATH="-cp .:"
CLASSPATH=$CLASSPATH:$RM_HOME_NODE/dist/lib/*
CLASSPATH=$CLASSPATH:$RM_HOME_NODE/addons

full_command="$HOST_NAME nohup $JAVA_PATH_NODE $JAVA_OPTS_NODE $CLASSPATH org.ow2.proactive.resourcemanager.utils.RMNodeStarter -v $CREDENTIALS -n $NODE_NAME -s $NODE_SOURCE_NAME -p 30000 -r $RM_URL"
echo "Running command using ssh $full_command"
ssh -o "StrictHostKeyChecking no" $full_command &

SSH_PID=$!
trap "kill $SSH_PID" TERM

# waiting until the process is killed
wait $SSH_PID
