import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;
import java.util.zip.ZipOutputStream;

/**
 * Patching class for the ProActive Scheduler.
 *
 * @author The ProActive Team
 * @version 1, Jan 8, 2008
 * @since ProActive 3.9
 */
public class Patch {
	private static String[] jarFiles = new String[]{"js.jar","script-api.jar","script-js.jar"};
	private static String ic2djar = "plugins/org.objectweb.proactive.ic2d.lib_1.0.0.jar";
	private static boolean fileNotExists(String jarPath){
		for (String s : jarFiles){
			if (!new File(jarPath,s).exists()){
				return true;
			}
		}
		return false;
	}
	private static boolean addEntry(File source, ZipOutputStream destination) {
		FileInputStream in = null;
		try {
			in = new FileInputStream(source);
			byte[] buf = new byte[1024];
			int len;
			while ((len = in.read(buf)) > 0) {
				destination.write(buf, 0, len);
			}
			return true;
		}
		catch (Exception e) {
			e.printStackTrace();
			return false;
		}
		finally {
			try {
				destination.closeEntry();
				in.close();
			}
			catch (IOException e) {
				e.printStackTrace();
				return false;
			}
		}
	}
	public static Result patch(String jarPath) {
		return patch(jarPath,false);
	}
	public static Result patch(String jarPath, boolean force) {
		try {
			//check ./Scheduler
			if (!(new File("Scheduler").exists()) && !(new File("Scheduler.exe").exists()) || !(new File(ic2djar).exists())){
				return new Result(false,"This patch must be executed\n in the ProActive Scheduler directory.");
			}
			//check files in jarPath
			if (!new File(jarPath).canRead() || fileNotExists(jarPath)){
				return new Result(false,"Required JSR-223 jar files (script-api.jar, script-js.jar and js.jar)\nare missing in '"+jarPath+"'.");
			}
			//check java 1.5
			if (!force && !(System.getProperty("java.version").split("[.]")[1].equals("5"))){
				return new Result(false,"This script is applicable only for Java 1.5 version.\nCurrent version is '"+System.getProperty("java.version")+"'. Patch anyway ?",true);
			}
			//patch ic2dLib jar
			new File("META-INF").mkdir();
			new File("META-INF/MANIFEST.MF").createNewFile();
			System.out.print("Creating MANIFEST.MF file...");
			PrintWriter manifest = null;
			try {
				manifest = new PrintWriter("META-INF/MANIFEST.MF");
				manifest.println(MANIFEST_CONTENT);
			} catch(Exception e) {
				e.printStackTrace();
				return new Result(false,"Enable to write the 'META-INF/MANIFEST.MF' file !");
			}
			finally{
				manifest.close();
				System.out.println("   OK !");
			}
			//copying jars
			System.out.println("Creating JAR...");
			ZipOutputStream jarDest = new ZipOutputStream(new FileOutputStream("tmp.jar"));
			ZipInputStream jarSrc = new ZipInputStream(new FileInputStream(ic2djar));
			ZipEntry ze = null;
			boolean alreadyPatch = false;
			while ((ze=jarSrc.getNextEntry()) != null){
				if (ze.getName().matches(".*"+jarFiles[0]+".*")){
					alreadyPatch = true;
				}
				if (!ze.getName().matches(".*MANIFEST.MF.*")){
					jarDest.putNextEntry(new ZipEntry(ze.getName()));
					byte[] buf = new byte[1024];
					int len;
					while ((len = jarSrc.read(buf,0,1024)) > 0) {
						jarDest.write(buf, 0, len);
					}
					jarSrc.closeEntry();
					jarDest.closeEntry();
				}
			}
			jarSrc.close();
			if (alreadyPatch){
				jarDest.close();
				new File("tmp.jar").delete();
				new File("META-INF/MANIFEST.MF").delete();
				new File("META-INF").delete();
				System.out.println("Already patched ! aborting...");
				return new Result(false,"The application seems to be already patched !");
			}
			System.out.println("Updating JAR...");
			for (String s : jarFiles){
				try {
					File f = new File(jarPath,s);
					jarDest.putNextEntry(new ZipEntry("lib/"+s));
					System.out.println("\tAdding "+s+" to jar..."+(addEntry(f, jarDest)?"   OK !":"   FAILED !"));
					jarDest.closeEntry();
				}
				catch (Exception e) {
					e.printStackTrace();
					return new Result(false,"An error occured while creating the jar !");
				}
			}
			//update manifest
			System.out.println("Updating manifest file in org.objectweb.proactive.ic2d.lib_1.0.0.jar...");
			try {
				File f = new File("META-INF/MANIFEST.MF");
				jarDest.putNextEntry(new ZipEntry("META-INF/MANIFEST.MF"));
				System.out.println("\tAdding MANIFEST.MF to jar : "+(addEntry(f, jarDest)?"   OK !":"   FAILED !"));
				jarDest.closeEntry();
			}
			catch (Exception e) {
				e.printStackTrace();
				return new Result(false,"An error occured while adding MANIFEST.MF jar file !");
			}
			jarDest.close();
			System.out.println("JAR completed successfully !");
			//move tmp.jar file
			System.out.print("Moving temp files...");
			new File(ic2djar).delete();
			new File("tmp.jar").renameTo(new File(ic2djar));
			System.out.println("   OK !");
			//remove temporary files
			System.out.print("Removing temp files...");
			new File("META-INF/MANIFEST.MF").delete();
			new File("META-INF").delete();
			System.out.println("   OK !");
			//patched !!
			System.out.println("Application has been successfully patched !");
			return new Result(true,"Application has been successfully patched !");
		} catch (IOException e){
			e.printStackTrace();
			return new Result(false,"An error occured while reading files on hard drive !");
		}
	}
	//Reading file into jars is not so simple so here's the manifest content.
	private static String MANIFEST_CONTENT = 
	"Manifest-Version: 1.0\n"+
	"Bundle-ManifestVersion: 2\n"+
	"Bundle-Name: ProActive Libraries\n"+
	"Bundle-SymbolicName: org.objectweb.proactive.ic2d.lib\n"+
	"Bundle-Version: 1.0.0\n"+
	"Bundle-Localization: plugin\n"+
	"Require-Bundle: org.eclipse.core.runtime,\n"+
	" org.eclipse.ui\n"+
	"Eclipse-BuddyPolicy: registered\n"+
	"Bundle-Vendor: ProActive\n"+
	"Bundle-ClassPath: lib/activation.jar,\n"+
	" lib/ajo.jar,\n"+
	" lib/asm-2.2.1.jar,\n"+
	" lib/axis.jar,\n"+
	" lib/batik-awt-util.jar,\n"+
	" lib/batik-dom.jar,\n"+
	" lib/batik-svggen.jar,\n"+
	" lib/batik-util.jar,\n"+
	" lib/batik-xml.jar,\n"+
	" lib/bouncycastle.jar,\n"+
	" lib/bundlerepository.jar,\n"+
	" lib/classad.jar,\n"+
	" lib/client.jar,\n"+
	" lib/cog-jglobus.jar,\n"+
	" lib/cog-jglobus-1.2.jar,\n"+
	" lib/cog-ogce.jar,\n"+
	" lib/colobus-0.1.jar,\n"+
	" lib/colt.jar,\n"+
	" lib/commons-cli-1.0.jar,\n"+
	" lib/commons-discovery.jar,\n"+
	" lib/commons-logging.jar,\n"+
	" lib/cryptix.jar,\n"+
	" lib/cryptix32.jar,\n"+
	" lib/cryptix-asn1.jar,\n"+
	" lib/derby.jar,\n"+
	" lib/derbytools.jar,\n"+
	" lib/dtdparser.jar,\n"+
	" lib/fractal.jar,\n"+
	" lib/fractal-adl.jar,\n"+
	" lib/ganymed-ssh2-build210.jar,\n"+
	" lib/glite-wms-jdlj.jar,\n"+
	" lib/http.jar,\n"+
	" lib/ibis-1.4.jar,\n"+
	" lib/ibis-connect-1.0.jar,\n"+
	" lib/ibis-util-1.0.jar,\n"+
	" lib/isorelax.jar,\n"+
	" lib/javasci.jar,\n"+
	" lib/javassist.jar,\n"+
	" lib/jaxrpc.jar,\n"+
	" lib/jcommon-1.0.6.jar,\n"+
	" lib/jdom.jar,\n"+
	" lib/jfreechart-1.0.2.jar,\n"+
	" lib/jh.jar,\n"+
	" lib/julia-asm.jar,\n"+
	" lib/julia-mixins.jar,\n"+
	" lib/julia-runtime.jar,\n"+
	" lib/jung-1.7.4.jar,\n"+
	" lib/log4j.jar,\n"+
	" lib/mail.jar,\n"+
	" lib/moduleloader.jar,\n"+
	" lib/msv.jar,\n"+
	" lib/njs_client.jar,\n"+
	" lib/oscar.jar,\n"+
	" lib/osgi.jar,\n"+
	" lib/ow_deployment_scheduling.jar,\n"+
	" lib/ptolemy.jar,\n"+
	" lib/puretls.jar,\n"+
	" lib/relaxngDatatype.jar,\n"+
	" lib/saaj-api.jar,\n"+
	" lib/saxon8.jar,\n"+
	" lib/saxon8-dom.jar,\n"+
	" lib/scriptPlugin.jar,\n"+
	" lib/servicebinder.jar,\n"+
	" lib/servlet.jar,\n"+
	" lib/servlet-api.jar,\n"+
	" lib/shell.jar,\n"+
	" lib/shellgui.jar,\n"+
	" lib/shellplugin.jar,\n"+
	" lib/shelltui.jar,\n"+
	" lib/simple.jar,\n"+
	" lib/soap.jar,\n"+
	" lib/sunxacml.jar,\n"+
	" lib/tablelayout.jar,\n"+
	" lib/wsdl4j.jar,\n"+
	" lib/xercesImpl.jar,\n"+
	" lib/xml-apis.jar,\n"+
	" lib/xsdlib.jar,\n"+
	" ProActive.jar,\n"+
	" lib/js.jar,\n"+
	" lib/script-api.jar,\n"+
	" lib/script-js.jar\n"+
	"Export-Package: .,\n"+
	" COM.claymoresystems.cert,\n"+
	" COM.claymoresystems.crypto,\n"+
	" COM.claymoresystems.provider,\n"+
	" COM.claymoresystems.provider.test,\n"+
	" COM.claymoresystems.ptls,\n"+
	" COM.claymoresystems.sslg,\n"+
	" COM.claymoresystems.util,\n"+
	" arcon.licence,\n"+
	" benchsocket,\n"+
	" cern.clhep,\n"+
	" cern.colt,\n"+
	" cern.colt.bitvector,\n"+
	" cern.colt.buffer,\n"+
	" cern.colt.function,\n"+
	" cern.colt.list,\n"+
	" cern.colt.list.adapter,\n"+
	" cern.colt.map,\n"+
	" cern.colt.matrix,\n"+
	" cern.colt.matrix.bench,\n"+
	" cern.colt.matrix.doublealgo,\n"+
	" cern.colt.matrix.impl,\n"+
	" cern.colt.matrix.linalg,\n"+
	" cern.colt.matrix.objectalgo,\n"+
	" cern.jet.math,\n"+
	" cern.jet.random,\n"+
	" cern.jet.random.engine,\n"+
	" cern.jet.random.sampling,\n"+
	" cern.jet.stat,\n"+
	" cern.jet.stat.quantile,\n"+
	" ch.ethz.ssh2,\n"+
	" ch.ethz.ssh2.auth,\n"+
	" ch.ethz.ssh2.channel,\n"+
	" ch.ethz.ssh2.crypto,\n"+
	" ch.ethz.ssh2.crypto.cipher,\n"+
	" ch.ethz.ssh2.crypto.dh,\n"+
	" ch.ethz.ssh2.crypto.digest,\n"+
	" ch.ethz.ssh2.log,\n"+
	" ch.ethz.ssh2.packets,\n"+
	" ch.ethz.ssh2.sftp,\n"+
	" ch.ethz.ssh2.signature,\n"+
	" ch.ethz.ssh2.transport,\n"+
	" ch.ethz.ssh2.util,\n"+
	" colobus,\n"+
	" colobus.eventViewer,\n"+
	" colobus.eventwriter,\n"+
	" colobus.eventwriter.console,\n"+
	" colobus.eventwriter.eventViewer,\n"+
	" colobus.eventwriter.file,\n"+
	" colobus.eventwriter.log4j,\n"+
	" com.fujitsu.arcon.njs.interfaces,\n"+
	" com.fujitsu.arcon.upl,\n"+
	" com.ibm.wsdl,\n"+
	" com.ibm.wsdl.extensions,\n"+
	" com.ibm.wsdl.extensions.http,\n"+
	" com.ibm.wsdl.extensions.mime,\n"+
	" com.ibm.wsdl.extensions.soap,\n"+
	" com.ibm.wsdl.factory,\n"+
	" com.ibm.wsdl.util,\n"+
	" com.ibm.wsdl.util.xml,\n"+
	" com.ibm.wsdl.xml,\n"+
	" com.keypoint,\n"+
	" com.pallas.ogsa.extensions,\n"+
	" com.pallas.ogsa.services.caservice,\n"+
	" com.pallas.ogsa.util,\n"+
	" com.pallas.security,\n"+
	" com.pallas.unicore.client,\n"+
	" com.pallas.unicore.client.controls,\n"+
	" com.pallas.unicore.client.dialogs,\n"+
	" com.pallas.unicore.client.editor,\n"+
	" com.pallas.unicore.client.explorer,\n"+
	" com.pallas.unicore.client.graphics,\n"+
	" com.pallas.unicore.client.graphs,\n"+
	" com.pallas.unicore.client.menus,\n"+
	" com.pallas.unicore.client.panels,\n"+
	" com.pallas.unicore.client.plugins.script,\n"+
	" com.pallas.unicore.client.remotefilechooser,\n"+
	" com.pallas.unicore.client.tables,\n"+
	" com.pallas.unicore.client.themes,\n"+
	" com.pallas.unicore.client.trees,\n"+
	" com.pallas.unicore.client.util,\n"+
	" com.pallas.unicore.client.xml,\n"+
	" com.pallas.unicore.connection,\n"+
	" com.pallas.unicore.container,\n"+
	" com.pallas.unicore.container.errorspec,\n"+
	" com.pallas.unicore.doc,\n"+
	" com.pallas.unicore.doc.manual,\n"+
	" com.pallas.unicore.doc.manual.JOBS,\n"+
	" com.pallas.unicore.doc.manual.JavaHelpSearch,\n"+
	" com.pallas.unicore.doc.manual.img,\n"+
	" com.pallas.unicore.doc.manual.install,\n"+
	" com.pallas.unicore.doc.manual.intro,\n"+
	" com.pallas.unicore.doc.manual.jmc,\n"+
	" com.pallas.unicore.doc.manual.jpa,\n"+
	" com.pallas.unicore.doc.manual.terms,\n"+
	" com.pallas.unicore.extensions,\n"+
	" com.pallas.unicore.img,\n"+
	" com.pallas.unicore.requests,\n"+
	" com.pallas.unicore.resourcemanager,\n"+
	" com.pallas.unicore.security,\n"+
	" com.pallas.unicore.threadpool,\n"+
	" com.pallas.unicore.utility,\n"+
	" com.sun.activation.registries,\n"+
	" com.sun.activation.viewers,\n"+
	" com.sun.java.help.impl,\n"+
	" com.sun.java.help.search,\n"+
	" com.sun.mail.handlers,\n"+
	" com.sun.mail.iap,\n"+
	" com.sun.mail.imap,\n"+
	" com.sun.mail.imap.protocol,\n"+
	" com.sun.mail.pop3,\n"+
	" com.sun.mail.smtp,\n"+
	" com.sun.mail.util,\n"+
	" com.sun.msv.datatype,\n"+
	" com.sun.msv.datatype.regexp,\n"+
	" com.sun.msv.datatype.xsd,\n"+
	" com.sun.msv.datatype.xsd.datetime,\n"+
	" com.sun.msv.datatype.xsd.ngimpl,\n"+
	" com.sun.msv.datatype.xsd.regex,\n"+
	" com.sun.msv.driver.textui,\n"+
	" com.sun.msv.grammar,\n"+
	" com.sun.msv.grammar.dtd,\n"+
	" com.sun.msv.grammar.relax,\n"+
	" com.sun.msv.grammar.relaxng,\n"+
	" com.sun.msv.grammar.relaxng.datatype,\n"+
	" com.sun.msv.grammar.trex,\n"+
	" com.sun.msv.grammar.trex.typed,\n"+
	" com.sun.msv.grammar.util,\n"+
	" com.sun.msv.grammar.xmlschema,\n"+
	" com.sun.msv.reader,\n"+
	" com.sun.msv.reader.datatype,\n"+
	" com.sun.msv.reader.datatype.xsd,\n"+
	" com.sun.msv.reader.dtd,\n"+
	" com.sun.msv.reader.relax,\n"+
	" com.sun.msv.reader.relax.core,\n"+
	" com.sun.msv.reader.relax.core.checker,\n"+
	" com.sun.msv.reader.trex,\n"+
	" com.sun.msv.reader.trex.classic,\n"+
	" com.sun.msv.reader.trex.ng,\n"+
	" com.sun.msv.reader.trex.ng.comp,\n"+
	" com.sun.msv.reader.trex.typed,\n"+
	" com.sun.msv.reader.util,\n"+
	" com.sun.msv.reader.xmlschema,\n"+
	" com.sun.msv.relaxns.grammar,\n"+
	" com.sun.msv.relaxns.grammar.relax,\n"+
	" com.sun.msv.relaxns.grammar.trex,\n"+
	" com.sun.msv.relaxns.reader,\n"+
	" com.sun.msv.relaxns.reader.relax,\n"+
	" com.sun.msv.relaxns.reader.trex,\n"+
	" com.sun.msv.relaxns.verifier,\n"+
	" com.sun.msv.scanner.dtd,\n"+
	" com.sun.msv.scanner.dtd.resources,\n"+
	" com.sun.msv.util,\n"+
	" com.sun.msv.util.xml,\n"+
	" com.sun.msv.verifier,\n"+
	" com.sun.msv.verifier.identity,\n"+
	" com.sun.msv.verifier.jarv,\n"+
	" com.sun.msv.verifier.jaxp,\n"+
	" com.sun.msv.verifier.psvi,\n"+
	" com.sun.msv.verifier.regexp,\n"+
	" com.sun.msv.verifier.regexp.xmlschema,\n"+
	" com.sun.msv.verifier.util,\n"+
	" com.sun.msv.writer,\n"+
	" com.sun.msv.writer.relaxng,\n"+
	" com.sun.script.javascript,\n"+
	" com.sun.script.util,\n"+
	" com.sun.xacml,\n"+
	" com.sun.xacml.attr,\n"+
	" com.sun.xacml.attr.proxy,\n"+
	" com.sun.xacml.combine,\n"+
	" com.sun.xacml.cond,\n"+
	" com.sun.xacml.cond.cluster,\n"+
	" com.sun.xacml.ctx,\n"+
	" com.sun.xacml.finder,\n"+
	" com.sun.xacml.finder.impl,\n"+
	" com.sun.xml.util,\n"+
	" com.wutka.dtd,\n"+
	" condor.classad,\n"+
	" corejava,\n"+
	" cryptix,\n"+
	" cryptix.asn1.encoding,\n"+
	" cryptix.asn1.lang,\n"+
	" cryptix.asn1.test,\n"+
	" cryptix.jce.provider,\n"+
	" cryptix.jce.provider.random,\n"+
	" cryptix.provider,\n"+
	" cryptix.provider.cipher,\n"+
	" cryptix.provider.elgamal,\n"+
	" cryptix.provider.key,\n"+
	" cryptix.provider.mac,\n"+
	" cryptix.provider.md,\n"+
	" cryptix.provider.mode,\n"+
	" cryptix.provider.padding,\n"+
	" cryptix.provider.rsa,\n"+
	" cryptix.test,\n"+
	" cryptix.tools,\n"+
	" cryptix.util.checksum,\n"+
	" cryptix.util.core,\n"+
	" cryptix.util.gui,\n"+
	" cryptix.util.io,\n"+
	" cryptix.util.math,\n"+
	" cryptix.util.mime,\n"+
	" cryptix.util.test,\n"+
	" diff,\n"+
	" doc,\n"+
	" edu.uci.ics.jung.algorithms,\n"+
	" edu.uci.ics.jung.algorithms.blockmodel,\n"+
	" edu.uci.ics.jung.algorithms.cluster,\n"+
	" edu.uci.ics.jung.algorithms.connectivity,\n"+
	" edu.uci.ics.jung.algorithms.flows,\n"+
	" edu.uci.ics.jung.algorithms.importance,\n"+
	" edu.uci.ics.jung.algorithms.metrics,\n"+
	" edu.uci.ics.jung.algorithms.shortestpath,\n"+
	" edu.uci.ics.jung.algorithms.transformation,\n"+
	" edu.uci.ics.jung.exceptions,\n"+
	" edu.uci.ics.jung.graph,\n"+
	" edu.uci.ics.jung.graph.decorators,\n"+
	" edu.uci.ics.jung.graph.event,\n"+
	" edu.uci.ics.jung.graph.filters,\n"+
	" edu.uci.ics.jung.graph.filters.impl,\n"+
	" edu.uci.ics.jung.graph.impl,\n"+
	" edu.uci.ics.jung.graph.predicates,\n"+
	" edu.uci.ics.jung.io,\n"+
	" edu.uci.ics.jung.random.generators,\n"+
	" edu.uci.ics.jung.random.permuters,\n"+
	" edu.uci.ics.jung.statistics,\n"+
	" edu.uci.ics.jung.utils,\n"+
	" edu.uci.ics.jung.visualization,\n"+
	" edu.uci.ics.jung.visualization.contrib,\n"+
	" edu.uci.ics.jung.visualization.control,\n"+
	" edu.uci.ics.jung.visualization.graphdraw,\n"+
	" edu.uci.ics.jung.visualization.subLayout,\n"+
	" edu.uci.ics.jung.visualization.transform,\n"+
	" edu.uci.ics.jung.visualization.transform.shape,\n"+
	" fr.imag.adele.metadataparser,\n"+
	" hep.aida,\n"+
	" hep.aida.bin,\n"+
	" hep.aida.ref,\n"+
	" ibis.connect,\n"+
	" ibis.connect.NIOParallelStreams,\n"+
	" ibis.connect.controlHub,\n"+
	" ibis.connect.parallelStreams,\n"+
	" ibis.connect.plainSocketFactories,\n"+
	" ibis.connect.routedMessages,\n"+
	" ibis.connect.tcpSplicing,\n"+
	" ibis.frontend.generic,\n"+
	" ibis.frontend.gmi,\n"+
	" ibis.frontend.ibis,\n"+
	" ibis.frontend.io,\n"+
	" ibis.frontend.repmi,\n"+
	" ibis.frontend.rmi,\n"+
	" ibis.frontend.satin,\n"+
	" ibis.gmi,\n"+
	" ibis.impl.messagePassing,\n"+
	" ibis.impl.messagePassing.mpi,\n"+
	" ibis.impl.messagePassing.panda,\n"+
	" ibis.impl.nameServer,\n"+
	" ibis.impl.nameServer.tcp,\n"+
	" ibis.impl.net,\n"+
	" ibis.impl.net.bytes,\n"+
	" ibis.impl.net.def,\n"+
	" ibis.impl.net.gen,\n"+
	" ibis.impl.net.gm,\n"+
	" ibis.impl.net.id,\n"+
	" ibis.impl.net.multi,\n"+
	" ibis.impl.net.multi.plugins,\n"+
	" ibis.impl.net.muxer,\n"+
	" ibis.impl.net.muxer.udp,\n"+
	" ibis.impl.net.pipe,\n"+
	" ibis.impl.net.rel,\n"+
	" ibis.impl.net.ser,\n"+
	" ibis.impl.net.tcp,\n"+
	" ibis.impl.net.tcp_blk,\n"+
	" ibis.impl.net.tcp_plain,\n"+
	" ibis.impl.net.udp,\n"+
	" ibis.impl.nio,\n"+
	" ibis.impl.tcp,\n"+
	" ibis.impl.test,\n"+
	" ibis.impl.util,\n"+
	" ibis.io,\n"+
	" ibis.io.nio,\n"+
	" ibis.ipl,\n"+
	" ibis.mpj,\n"+
	" ibis.rmi,\n"+
	" ibis.rmi.impl,\n"+
	" ibis.rmi.registry,\n"+
	" ibis.rmi.registry.impl,\n"+
	" ibis.rmi.server,\n"+
	" ibis.satin,\n"+
	" ibis.satin.impl,\n"+
	" ibis.satin.impl.aborts,\n"+
	" ibis.satin.impl.communication,\n"+
	" ibis.satin.impl.faultTolerance,\n"+
	" ibis.satin.impl.loadBalancing,\n"+
	" ibis.satin.impl.sharedObjects,\n"+
	" ibis.satin.impl.spawnSync,\n"+
	" ibis.util,\n"+
	" ibis.util.messagecombining,\n"+
	" ibis.util.nativeCode,\n"+
	" images,\n"+
	" include,\n"+
	" info.clearthought.layout,\n"+
	" javasci,\n"+
	" javassist,\n"+
	" javassist.bytecode,\n"+
	" javassist.bytecode.annotation,\n"+
	" javassist.compiler,\n"+
	" javassist.compiler.ast,\n"+
	" javassist.convert,\n"+
	" javassist.expr,\n"+
	" javassist.runtime,\n"+
	" javassist.scopedpool,\n"+
	" javassist.tools,\n"+
	" javassist.tools.reflect,\n"+
	" javassist.tools.rmi,\n"+
	" javassist.tools.web,\n"+
	" javassist.util,\n"+
	" javassist.util.proxy,\n"+
	" javax.activation,\n"+
	" javax.help,\n"+
	" javax.help.event,\n"+
	" javax.help.plaf,\n"+
	" javax.help.plaf.basic,\n"+
	" javax.help.plaf.basic.images,\n"+
	" javax.help.resources,\n"+
	" javax.help.search,\n"+
	" javax.mail,\n"+
	" javax.mail.event,\n"+
	" javax.mail.internet,\n"+
	" javax.mail.search,\n"+
	" javax.script,\n"+
	" javax.servlet,\n"+
	" javax.servlet.http,\n"+
	" javax.servlet.resources,\n"+
	" javax.wsdl,\n"+
	" javax.wsdl.extensions,\n"+
	" javax.wsdl.extensions.http,\n"+
	" javax.wsdl.extensions.mime,\n"+
	" javax.wsdl.extensions.soap,\n"+
	" javax.wsdl.factory,\n"+
	" javax.wsdl.xml,\n"+
	" javax.xml,\n"+
	" javax.xml.datatype,\n"+
	" javax.xml.messaging,\n"+
	" javax.xml.namespace,\n"+
	" javax.xml.parsers,\n"+
	" javax.xml.rpc,\n"+
	" javax.xml.rpc.encoding,\n"+
	" javax.xml.rpc.handler,\n"+
	" javax.xml.rpc.handler.soap,\n"+
	" javax.xml.rpc.holders,\n"+
	" javax.xml.rpc.server,\n"+
	" javax.xml.rpc.soap,\n"+
	" javax.xml.soap,\n"+
	" javax.xml.transform,\n"+
	" javax.xml.transform.dom,\n"+
	" javax.xml.transform.sax,\n"+
	" javax.xml.transform.stream,\n"+
	" javax.xml.validation,\n"+
	" javax.xml.xpath,\n"+
	" jp.gr.xml.relax.dom,\n"+
	" jp.gr.xml.relax.lib,\n"+
	" jp.gr.xml.relax.sax,\n"+
	" jp.gr.xml.relax.swift,\n"+
	" jp.gr.xml.relax.xml,\n"+
	" kxml.sax,\n"+
	" license,\n"+
	" net.sf.saxon,\n"+
	" net.sf.saxon.charcode,\n"+
	" net.sf.saxon.codenorm,\n"+
	" net.sf.saxon.dom,\n"+
	" net.sf.saxon.event,\n"+
	" net.sf.saxon.expr,\n"+
	" net.sf.saxon.exslt,\n"+
	" net.sf.saxon.functions,\n"+
	" net.sf.saxon.instruct,\n"+
	" net.sf.saxon.java,\n"+
	" net.sf.saxon.number,\n"+
	" net.sf.saxon.om,\n"+
	" net.sf.saxon.pattern,\n"+
	" net.sf.saxon.pull,\n"+
	" net.sf.saxon.query,\n"+
	" net.sf.saxon.regex,\n"+
	" net.sf.saxon.sort,\n"+
	" net.sf.saxon.style,\n"+
	" net.sf.saxon.sxpath,\n"+
	" net.sf.saxon.tinytree,\n"+
	" net.sf.saxon.trace,\n"+
	" net.sf.saxon.trans,\n"+
	" net.sf.saxon.tree,\n"+
	" net.sf.saxon.type,\n"+
	" net.sf.saxon.value,\n"+
	" netscape.security,\n"+
	" org.apache.axis,\n"+
	" org.apache.axis.attachments,\n"+
	" org.apache.axis.client,\n"+
	" org.apache.axis.collections,\n"+
	" org.apache.axis.components.compiler,\n"+
	" org.apache.axis.components.encoding,\n"+
	" org.apache.axis.components.image,\n"+
	" org.apache.axis.components.jms,\n"+
	" org.apache.axis.components.logger,\n"+
	" org.apache.axis.components.net,\n"+
	" org.apache.axis.components.script,\n"+
	" org.apache.axis.components.threadpool,\n"+
	" org.apache.axis.components.uuid,\n"+
	" org.apache.axis.configuration,\n"+
	" org.apache.axis.deployment.wsdd,\n"+
	" org.apache.axis.deployment.wsdd.providers,\n"+
	" org.apache.axis.description,\n"+
	" org.apache.axis.encoding,\n"+
	" org.apache.axis.encoding.ser,\n"+
	" org.apache.axis.handlers,\n"+
	" org.apache.axis.handlers.http,\n"+
	" org.apache.axis.handlers.soap,\n"+
	" org.apache.axis.holders,\n"+
	" org.apache.axis.i18n,\n"+
	" org.apache.axis.management,\n"+
	" org.apache.axis.message,\n"+
	" org.apache.axis.monitor,\n"+
	" org.apache.axis.providers,\n"+
	" org.apache.axis.providers.java,\n"+
	" org.apache.axis.schema,\n"+
	" org.apache.axis.security,\n"+
	" org.apache.axis.security.servlet,\n"+
	" org.apache.axis.security.simple,\n"+
	" org.apache.axis.server,\n"+
	" org.apache.axis.session,\n"+
	" org.apache.axis.soap,\n"+
	" org.apache.axis.strategies,\n"+
	" org.apache.axis.transport.http,\n"+
	" org.apache.axis.transport.java,\n"+
	" org.apache.axis.transport.jms,\n"+
	" org.apache.axis.transport.local,\n"+
	" org.apache.axis.types,\n"+
	" org.apache.axis.utils,\n"+
	" org.apache.axis.utils.bytecode,\n"+
	" org.apache.axis.utils.cache,\n"+
	" org.apache.axis.wsdl,\n"+
	" org.apache.axis.wsdl.fromJava,\n"+
	" org.apache.axis.wsdl.gen,\n"+
	" org.apache.axis.wsdl.symbolTable,\n"+
	" org.apache.axis.wsdl.toJava,\n"+
	" org.apache.batik,\n"+
	" org.apache.batik.dom,\n"+
	" org.apache.batik.dom.events,\n"+
	" org.apache.batik.dom.resources,\n"+
	" org.apache.batik.dom.traversal,\n"+
	" org.apache.batik.dom.util,\n"+
	" org.apache.batik.ext.awt,\n"+
	" org.apache.batik.ext.awt.color,\n"+
	" org.apache.batik.ext.awt.font,\n"+
	" org.apache.batik.ext.awt.g2d,\n"+
	" org.apache.batik.ext.awt.geom,\n"+
	" org.apache.batik.ext.awt.image,\n"+
	" org.apache.batik.ext.awt.image.codec,\n"+
	" org.apache.batik.ext.awt.image.codec.tiff,\n"+
	" org.apache.batik.ext.awt.image.renderable,\n"+
	" org.apache.batik.ext.awt.image.rendered,\n"+
	" org.apache.batik.ext.awt.image.spi,\n"+
	" org.apache.batik.ext.awt.image.spi.resources,\n"+
	" org.apache.batik.ext.swing,\n"+
	" org.apache.batik.ext.swing.resources,\n"+
	" org.apache.batik.i18n,\n"+
	" org.apache.batik.svggen,\n"+
	" org.apache.batik.svggen.font,\n"+
	" org.apache.batik.svggen.font.resources,\n"+
	" org.apache.batik.svggen.font.table,\n"+
	" org.apache.batik.util,\n"+
	" org.apache.batik.util.io,\n"+
	" org.apache.batik.util.io.resources,\n"+
	" org.apache.batik.util.resources,\n"+
	" org.apache.batik.xml,\n"+
	" org.apache.batik.xml.scanner.resources,\n"+
	" org.apache.commons.cli,\n"+
	" org.apache.commons.discovery,\n"+
	" org.apache.commons.discovery.ant,\n"+
	" org.apache.commons.discovery.jdk,\n"+
	" org.apache.commons.discovery.log,\n"+
	" org.apache.commons.discovery.resource,\n"+
	" org.apache.commons.discovery.resource.classes,\n"+
	" org.apache.commons.discovery.resource.names,\n"+
	" org.apache.commons.discovery.tools,\n"+
	" org.apache.commons.logging,\n"+
	" org.apache.commons.logging.impl,\n"+
	" org.apache.derby,\n"+
	" org.apache.derby.authentication,\n"+
	" org.apache.derby.catalog,\n"+
	" org.apache.derby.catalog.types,\n"+
	" org.apache.derby.database,\n"+
	" org.apache.derby.diag,\n"+
	" org.apache.derby.iapi.db,\n"+
	" org.apache.derby.iapi.error,\n"+
	" org.apache.derby.iapi.jdbc,\n"+
	" org.apache.derby.iapi.reference,\n"+
	" org.apache.derby.iapi.services.cache,\n"+
	" org.apache.derby.iapi.services.classfile,\n"+
	" org.apache.derby.iapi.services.compiler,\n"+
	" org.apache.derby.iapi.services.context,\n"+
	" org.apache.derby.iapi.services.crypto,\n"+
	" org.apache.derby.iapi.services.daemon,\n"+
	" org.apache.derby.iapi.services.diag,\n"+
	" org.apache.derby.iapi.services.i18n,\n"+
	" org.apache.derby.iapi.services.info,\n"+
	" org.apache.derby.iapi.services.io,\n"+
	" org.apache.derby.iapi.services.loader,\n"+
	" org.apache.derby.iapi.services.locks,\n"+
	" org.apache.derby.iapi.services.memory,\n"+
	" org.apache.derby.iapi.services.monitor,\n"+
	" org.apache.derby.iapi.services.property,\n"+
	" org.apache.derby.iapi.services.stream,\n"+
	" org.apache.derby.iapi.services.timer,\n"+
	" org.apache.derby.iapi.services.uuid,\n"+
	" org.apache.derby.iapi.sql,\n"+
	" org.apache.derby.iapi.sql.compile,\n"+
	" org.apache.derby.iapi.sql.conn,\n"+
	" org.apache.derby.iapi.sql.depend,\n"+
	" org.apache.derby.iapi.sql.dictionary,\n"+
	" org.apache.derby.iapi.sql.execute,\n"+
	" org.apache.derby.iapi.store.access,\n"+
	" org.apache.derby.iapi.store.access.conglomerate,\n"+
	" org.apache.derby.iapi.store.access.xa,\n"+
	" org.apache.derby.iapi.store.raw,\n"+
	" org.apache.derby.iapi.store.raw.data,\n"+
	" org.apache.derby.iapi.store.raw.log,\n"+
	" org.apache.derby.iapi.store.raw.xact,\n"+
	" org.apache.derby.iapi.tools.i18n,\n"+
	" org.apache.derby.iapi.types,\n"+
	" org.apache.derby.iapi.util,\n"+
	" org.apache.derby.impl.db,\n"+
	" org.apache.derby.impl.io,\n"+
	" org.apache.derby.impl.jdbc,\n"+
	" org.apache.derby.impl.jdbc.authentication,\n"+
	" org.apache.derby.impl.load,\n"+
	" org.apache.derby.impl.services.bytecode,\n"+
	" org.apache.derby.impl.services.cache,\n"+
	" org.apache.derby.impl.services.daemon,\n"+
	" org.apache.derby.impl.services.jce,\n"+
	" org.apache.derby.impl.services.locks,\n"+
	" org.apache.derby.impl.services.monitor,\n"+
	" org.apache.derby.impl.services.reflect,\n"+
	" org.apache.derby.impl.services.stream,\n"+
	" org.apache.derby.impl.services.timer,\n"+
	" org.apache.derby.impl.services.uuid,\n"+
	" org.apache.derby.impl.sql,\n"+
	" org.apache.derby.impl.sql.catalog,\n"+
	" org.apache.derby.impl.sql.compile,\n"+
	" org.apache.derby.impl.sql.conn,\n"+
	" org.apache.derby.impl.sql.depend,\n"+
	" org.apache.derby.impl.sql.execute,\n"+
	" org.apache.derby.impl.sql.execute.rts,\n"+
	" org.apache.derby.impl.store.access,\n"+
	" org.apache.derby.impl.store.access.btree,\n"+
	" org.apache.derby.impl.store.access.btree.index,\n"+
	" org.apache.derby.impl.store.access.conglomerate,\n"+
	" org.apache.derby.impl.store.access.heap,\n"+
	" org.apache.derby.impl.store.access.sort,\n"+
	" org.apache.derby.impl.store.raw,\n"+
	" org.apache.derby.impl.store.raw.data,\n"+
	" org.apache.derby.impl.store.raw.log,\n"+
	" org.apache.derby.impl.store.raw.xact,\n"+
	" org.apache.derby.impl.tools.dblook,\n"+
	" org.apache.derby.impl.tools.ij,\n"+
	" org.apache.derby.impl.tools.sysinfo,\n"+
	" org.apache.derby.info,\n"+
	" org.apache.derby.io,\n"+
	" org.apache.derby.jdbc,\n"+
	" org.apache.derby.loc,\n"+
	" org.apache.derby.osgi,\n"+
	" org.apache.derby.shared.common.error,\n"+
	" org.apache.derby.tools,\n"+
	" org.apache.derby.vti,\n"+
	" org.apache.html.dom,\n"+
	" org.apache.log4j,\n"+
	" org.apache.log4j.chainsaw,\n"+
	" org.apache.log4j.config,\n"+
	" org.apache.log4j.helpers,\n"+
	" org.apache.log4j.jdbc,\n"+
	" org.apache.log4j.jmx,\n"+
	" org.apache.log4j.lf5,\n"+
	" org.apache.log4j.lf5.config,\n"+
	" org.apache.log4j.lf5.util,\n"+
	" org.apache.log4j.lf5.viewer,\n"+
	" org.apache.log4j.lf5.viewer.categoryexplorer,\n"+
	" org.apache.log4j.lf5.viewer.configure,\n"+
	" org.apache.log4j.lf5.viewer.images,\n"+
	" org.apache.log4j.net,\n"+
	" org.apache.log4j.nt,\n"+
	" org.apache.log4j.or,\n"+
	" org.apache.log4j.or.jms,\n"+
	" org.apache.log4j.or.sax,\n"+
	" org.apache.log4j.spi,\n"+
	" org.apache.log4j.varia,\n"+
	" org.apache.log4j.xml,\n"+
	" org.apache.soap,\n"+
	" org.apache.soap.encoding,\n"+
	" org.apache.soap.encoding.literalxml,\n"+
	" org.apache.soap.encoding.soapenc,\n"+
	" org.apache.soap.encoding.xmi,\n"+
	" org.apache.soap.messaging,\n"+
	" org.apache.soap.providers,\n"+
	" org.apache.soap.providers.com,\n"+
	" org.apache.soap.rpc,\n"+
	" org.apache.soap.server,\n"+
	" org.apache.soap.server.http,\n"+
	" org.apache.soap.transport,\n"+
	" org.apache.soap.transport.http,\n"+
	" org.apache.soap.transport.smtp,\n"+
	" org.apache.soap.util,\n"+
	" org.apache.soap.util.mime,\n"+
	" org.apache.soap.util.net,\n"+
	" org.apache.soap.util.xml,\n"+
	" org.apache.wml,\n"+
	" org.apache.wml.dom,\n"+
	" org.apache.xerces.dom,\n"+
	" org.apache.xerces.dom.events,\n"+
	" org.apache.xerces.dom3.as,\n"+
	" org.apache.xerces.impl,\n"+
	" org.apache.xerces.impl.dtd,\n"+
	" org.apache.xerces.impl.dtd.models,\n"+
	" org.apache.xerces.impl.dv,\n"+
	" org.apache.xerces.impl.dv.dtd,\n"+
	" org.apache.xerces.impl.dv.util,\n"+
	" org.apache.xerces.impl.dv.xs,\n"+
	" org.apache.xerces.impl.io,\n"+
	" org.apache.xerces.impl.msg,\n"+
	" org.apache.xerces.impl.validation,\n"+
	" org.apache.xerces.impl.xpath,\n"+
	" org.apache.xerces.impl.xpath.regex,\n"+
	" org.apache.xerces.impl.xs,\n"+
	" org.apache.xerces.impl.xs.identity,\n"+
	" org.apache.xerces.impl.xs.models,\n"+
	" org.apache.xerces.impl.xs.opti,\n"+
	" org.apache.xerces.impl.xs.traversers,\n"+
	" org.apache.xerces.impl.xs.util,\n"+
	" org.apache.xerces.jaxp,\n"+
	" org.apache.xerces.jaxp.datatype,\n"+
	" org.apache.xerces.jaxp.validation,\n"+
	" org.apache.xerces.parsers,\n"+
	" org.apache.xerces.util,\n"+
	" org.apache.xerces.xinclude,\n"+
	" org.apache.xerces.xni,\n"+
	" org.apache.xerces.xni.grammars,\n"+
	" org.apache.xerces.xni.parser,\n"+
	" org.apache.xerces.xpointer,\n"+
	" org.apache.xerces.xs,\n"+
	" org.apache.xerces.xs.datatypes,\n"+
	" org.apache.xml.serialize,\n"+
	" org.apache.xml.xml_soap,\n"+
	" org.apache.xmlcommons,\n"+
	" org.bouncycastle,\n"+
	" org.bouncycastle.asn1,\n"+
	" org.bouncycastle.asn1.cmp,\n"+
	" org.bouncycastle.asn1.cms,\n"+
	" org.bouncycastle.asn1.cryptopro,\n"+
	" org.bouncycastle.asn1.esf,\n"+
	" org.bouncycastle.asn1.ess,\n"+
	" org.bouncycastle.asn1.gnu,\n"+
	" org.bouncycastle.asn1.iana,\n"+
	" org.bouncycastle.asn1.icao,\n"+
	" org.bouncycastle.asn1.isismtt,\n"+
	" org.bouncycastle.asn1.isismtt.ocsp,\n"+
	" org.bouncycastle.asn1.isismtt.x509,\n"+
	" org.bouncycastle.asn1.kisa,\n"+
	" org.bouncycastle.asn1.microsoft,\n"+
	" org.bouncycastle.asn1.misc,\n"+
	" org.bouncycastle.asn1.mozilla,\n"+
	" org.bouncycastle.asn1.nist,\n"+
	" org.bouncycastle.asn1.ntt,\n"+
	" org.bouncycastle.asn1.ocsp,\n"+
	" org.bouncycastle.asn1.oiw,\n"+
	" org.bouncycastle.asn1.pkcs,\n"+
	" org.bouncycastle.asn1.sec,\n"+
	" org.bouncycastle.asn1.smime,\n"+
	" org.bouncycastle.asn1.teletrust,\n"+
	" org.bouncycastle.asn1.tsp,\n"+
	" org.bouncycastle.asn1.util,\n"+
	" org.bouncycastle.asn1.x500,\n"+
	" org.bouncycastle.asn1.x509,\n"+
	" org.bouncycastle.asn1.x509.qualified,\n"+
	" org.bouncycastle.asn1.x509.sigi,\n"+
	" org.bouncycastle.asn1.x9,\n"+
	" org.bouncycastle.crypto,\n"+
	" org.bouncycastle.crypto.agreement,\n"+
	" org.bouncycastle.crypto.agreement.kdf,\n"+
	" org.bouncycastle.crypto.digests,\n"+
	" org.bouncycastle.crypto.encodings,\n"+
	" org.bouncycastle.crypto.engines,\n"+
	" org.bouncycastle.crypto.examples,\n"+
	" org.bouncycastle.crypto.generators,\n"+
	" org.bouncycastle.crypto.io,\n"+
	" org.bouncycastle.crypto.macs,\n"+
	" org.bouncycastle.crypto.modes,\n"+
	" org.bouncycastle.crypto.paddings,\n"+
	" org.bouncycastle.crypto.params,\n"+
	" org.bouncycastle.crypto.prng,\n"+
	" org.bouncycastle.crypto.signers,\n"+
	" org.bouncycastle.crypto.tls,\n"+
	" org.bouncycastle.crypto.util,\n"+
	" org.bouncycastle.i18n,\n"+
	" org.bouncycastle.i18n.filter,\n"+
	" org.bouncycastle.jce,\n"+
	" org.bouncycastle.jce.examples,\n"+
	" org.bouncycastle.jce.exception,\n"+
	" org.bouncycastle.jce.interfaces,\n"+
	" org.bouncycastle.jce.netscape,\n"+
	" org.bouncycastle.jce.provider,\n"+
	" org.bouncycastle.jce.provider.symmetric,\n"+
	" org.bouncycastle.jce.spec,\n"+
	" org.bouncycastle.math.ec,\n"+
	" org.bouncycastle.mozilla,\n"+
	" org.bouncycastle.ocsp,\n"+
	" org.bouncycastle.openssl,\n"+
	" org.bouncycastle.util,\n"+
	" org.bouncycastle.util.encoders,\n"+
	" org.bouncycastle.util.test,\n"+
	" org.bouncycastle.voms,\n"+
	" org.bouncycastle.x509,\n"+
	" org.bouncycastle.x509.examples,\n"+
	" org.bouncycastle.x509.extension,\n"+
	" org.bouncycastle.x509.util,\n"+
	" org.glite.wms.jdlj,\n"+
	" org.globus.cog.reservation,\n"+
	" org.globus.common,\n"+
	" org.globus.examples,\n"+
	" org.globus.ftp,\n"+
	" org.globus.ftp.app,\n"+
	" org.globus.ftp.dc,\n"+
	" org.globus.ftp.exception,\n"+
	" org.globus.ftp.extended,\n"+
	" org.globus.ftp.vanilla,\n"+
	" org.globus.gara,\n"+
	" org.globus.gara.internal,\n"+
	" org.globus.gatekeeper,\n"+
	" org.globus.gatekeeper.internal,\n"+
	" org.globus.gatekeeper.jobmanager,\n"+
	" org.globus.gatekeeper.jobmanager.internal,\n"+
	" org.globus.gram,\n"+
	" org.globus.gram.internal,\n"+
	" org.globus.gsi,\n"+
	" org.globus.gsi.bc,\n"+
	" org.globus.gsi.gssapi,\n"+
	" org.globus.gsi.gssapi.auth,\n"+
	" org.globus.gsi.gssapi.example,\n"+
	" org.globus.gsi.gssapi.net,\n"+
	" org.globus.gsi.gssapi.net.example,\n"+
	" org.globus.gsi.gssapi.net.impl,\n"+
	" org.globus.gsi.jaas,\n"+
	" org.globus.gsi.proxy,\n"+
	" org.globus.gsi.proxy.ext,\n"+
	" org.globus.gsi.ptls,\n"+
	" org.globus.io.gass.client,\n"+
	" org.globus.io.gass.client.internal,\n"+
	" org.globus.io.gass.server,\n"+
	" org.globus.io.streams,\n"+
	" org.globus.io.urlcopy,\n"+
	" org.globus.mds,\n"+
	" org.globus.mds.gsi,\n"+
	" org.globus.mds.gsi.common,\n"+
	" org.globus.mds.gsi.jndi,\n"+
	" org.globus.mds.gsi.netscape,\n"+
	" org.globus.myproxy,\n"+
	" org.globus.net,\n"+
	" org.globus.net.protocol.httpg,\n"+
	" org.globus.ogce,\n"+
	" org.globus.ogce.ant,\n"+
	" org.globus.ogce.beans.about,\n"+
	" org.globus.ogce.beans.console.gui,\n"+
	" org.globus.ogce.beans.console.gui.commands,\n"+
	" org.globus.ogce.beans.console.gui.commands.grid,\n"+
	" org.globus.ogce.beans.console.gui.ftp,\n"+
	" org.globus.ogce.beans.console.gui.util,\n"+
	" org.globus.ogce.beans.execute,\n"+
	" org.globus.ogce.beans.filetransfer,\n"+
	" org.globus.ogce.beans.filetransfer.gui,\n"+
	" org.globus.ogce.beans.filetransfer.gui.local,\n"+
	" org.globus.ogce.beans.filetransfer.gui.monitor,\n"+
	" org.globus.ogce.beans.filetransfer.gui.remote.common,\n"+
	" org.globus.ogce.beans.filetransfer.gui.remote.ftp,\n"+
	" org.globus.ogce.beans.filetransfer.gui.remote.gridftp,\n"+
	" org.globus.ogce.beans.filetransfer.transfer,\n"+
	" org.globus.ogce.beans.filetransfer.util,\n"+
	" org.globus.ogce.beans.floweditor.flowelement,\n"+
	" org.globus.ogce.beans.floweditor.flowelementrenderer,\n"+
	" org.globus.ogce.beans.floweditor.flowobject,\n"+
	" org.globus.ogce.beans.floweditor.flowtype,\n"+
	" org.globus.ogce.beans.floweditor.popupeditor,\n"+
	" org.globus.ogce.beans.floweditor.runner,\n"+
	" org.globus.ogce.beans.floweditor.schemareader,\n"+
	" org.globus.ogce.beans.floweditor.userinterface,\n"+
	" org.globus.ogce.beans.information.tree,\n"+
	" org.globus.ogce.beans.transfer.reliable,\n"+
	" org.globus.ogce.broker,\n"+
	" org.globus.ogce.broker.messages,\n"+
	" org.globus.ogce.broker.policy,\n"+
	" org.globus.ogce.broker.server,\n"+
	" org.globus.ogce.broker.util,\n"+
	" org.globus.ogce.broker.util.jobset,\n"+
	" org.globus.ogce.common,\n"+
	" org.globus.ogce.gui.awt,\n"+
	" org.globus.ogce.gui.awt.datatransfer,\n"+
	" org.globus.ogce.gui.desktop,\n"+
	" org.globus.ogce.gui.desktop.images,\n"+
	" org.globus.ogce.gui.desktop.interfaces,\n"+
	" org.globus.ogce.gui.dnd,\n"+
	" org.globus.ogce.gui.dnd.images,\n"+
	" org.globus.ogce.gui.gram.gui,\n"+
	" org.globus.ogce.gui.grapheditor,\n"+
	" org.globus.ogce.gui.grapheditor.ant,\n"+
	" org.globus.ogce.gui.grapheditor.ant.taskdefs,\n"+
	" org.globus.ogce.gui.grapheditor.canvas,\n"+
	" org.globus.ogce.gui.grapheditor.canvas.transformation,\n"+
	" org.globus.ogce.gui.grapheditor.canvas.views,\n"+
	" org.globus.ogce.gui.grapheditor.edges,\n"+
	" org.globus.ogce.gui.grapheditor.generic,\n"+
	" org.globus.ogce.gui.grapheditor.nodes,\n"+
	" org.globus.ogce.gui.grapheditor.util,\n"+
	" org.globus.ogce.gui.grapheditor.util.celleditors,\n"+
	" org.globus.ogce.gui.grapheditor.util.graphics,\n"+
	" org.globus.ogce.gui.setup,\n"+
	" org.globus.ogce.gui.setup.examples,\n"+
	" org.globus.ogce.gui.swing,\n"+
	" org.globus.ogce.gui.util,\n"+
	" org.globus.ogce.gui.util.graph,\n"+
	" org.globus.ogce.gui.util.timer,\n"+
	" org.globus.ogce.gui.xml,\n"+
	" org.globus.ogce.test,\n"+
	" org.globus.ogce.util,\n"+
	" org.globus.ogce.util.graph,\n"+
	" org.globus.ogce.util.graph.example,\n"+
	" org.globus.ogce.util.tree,\n"+
	" org.globus.ogce.util.tree.example,\n"+
	" org.globus.replica.catalog,\n"+
	" org.globus.rsl,\n"+
	" org.globus.security.gridmap,\n"+
	" org.globus.test.bigType,\n"+
	" org.globus.test.otherTypes,\n"+
	" org.globus.tools,\n"+
	" org.globus.tools.proxy,\n"+
	" org.globus.tools.ui.config,\n"+
	" org.globus.tools.ui.swing,\n"+
	" org.globus.tools.ui.util,\n"+
	" org.globus.util,\n"+
	" org.globus.util.deactivator,\n"+
	" org.globus.util.debug,\n"+
	" org.globus.util.http,\n"+
	" org.globus.util.log4j,\n"+
	" org.gridforum.jgss,\n"+
	" org.iso_relax.ant,\n"+
	" org.iso_relax.catalog,\n"+
	" org.iso_relax.dispatcher,\n"+
	" org.iso_relax.dispatcher.impl,\n"+
	" org.iso_relax.jaxp,\n"+
	" org.iso_relax.verifier,\n"+
	" org.iso_relax.verifier.impl,\n"+
	" org.jdom,\n"+
	" org.jdom.adapters,\n"+
	" org.jdom.filter,\n"+
	" org.jdom.input,\n"+
	" org.jdom.output,\n"+
	" org.jdom.transform,\n"+
	" org.jdom.xpath,\n"+
	" org.jfree,\n"+
	" org.jfree.base,\n"+
	" org.jfree.base.config,\n"+
	" org.jfree.base.log,\n"+
	" org.jfree.base.modules,\n"+
	" org.jfree.chart,\n"+
	" org.jfree.chart.annotations,\n"+
	" org.jfree.chart.axis,\n"+
	" org.jfree.chart.block,\n"+
	" org.jfree.chart.demo,\n"+
	" org.jfree.chart.editor,\n"+
	" org.jfree.chart.encoders,\n"+
	" org.jfree.chart.entity,\n"+
	" org.jfree.chart.event,\n"+
	" org.jfree.chart.imagemap,\n"+
	" org.jfree.chart.labels,\n"+
	" org.jfree.chart.needle,\n"+
	" org.jfree.chart.plot,\n"+
	" org.jfree.chart.renderer,\n"+
	" org.jfree.chart.renderer.category,\n"+
	" org.jfree.chart.renderer.xy,\n"+
	" org.jfree.chart.resources,\n"+
	" org.jfree.chart.servlet,\n"+
	" org.jfree.chart.title,\n"+
	" org.jfree.chart.urls,\n"+
	" org.jfree.data,\n"+
	" org.jfree.data.category,\n"+
	" org.jfree.data.contour,\n"+
	" org.jfree.data.function,\n"+
	" org.jfree.data.gantt,\n"+
	" org.jfree.data.general,\n"+
	" org.jfree.data.io,\n"+
	" org.jfree.data.jdbc,\n"+
	" org.jfree.data.resources,\n"+
	" org.jfree.data.statistics,\n"+
	" org.jfree.data.time,\n"+
	" org.jfree.data.xml,\n"+
	" org.jfree.data.xy,\n"+
	" org.jfree.date,\n"+
	" org.jfree.io,\n"+
	" org.jfree.layout,\n"+
	" org.jfree.resources,\n"+
	" org.jfree.text,\n"+
	" org.jfree.threads,\n"+
	" org.jfree.ui,\n"+
	" org.jfree.ui.about,\n"+
	" org.jfree.ui.about.resources,\n"+
	" org.jfree.ui.action,\n"+
	" org.jfree.ui.tabbedui,\n"+
	" org.jfree.util,\n"+
	" org.mortbay.jetty.servlet,\n"+
	" org.mozilla.classfile,\n"+
	" org.mozilla.javascript,\n"+
	" org.mozilla.javascript.continuations,\n"+
	" org.mozilla.javascript.debug,\n"+
	" org.mozilla.javascript.jdk11,\n"+
	" org.mozilla.javascript.jdk13,\n"+
	" org.mozilla.javascript.optimizer,\n"+
	" org.mozilla.javascript.regexp,\n"+
	" org.mozilla.javascript.resources,\n"+
	" org.mozilla.javascript.serialize,\n"+
	" org.mozilla.javascript.tools,\n"+
	" org.mozilla.javascript.tools.debugger,\n"+
	" org.mozilla.javascript.tools.debugger.downloaded,\n"+
	" org.mozilla.javascript.tools.idswitch,\n"+
	" org.mozilla.javascript.tools.jsc,\n"+
	" org.mozilla.javascript.tools.resources,\n"+
	" org.mozilla.javascript.tools.shell,\n"+
	" org.mozilla.javascript.xml,\n"+
	" org.mozilla.javascript.xmlimpl,\n"+
	" org.objectweb.asm,\n"+
	" org.objectweb.asm.signature,\n"+
	" org.objectweb.deployment.scheduling.component.api,\n"+
	" org.objectweb.deployment.scheduling.component.lib,\n"+
	" org.objectweb.deployment.scheduling.core.api,\n"+
	" org.objectweb.deployment.scheduling.core.lib,\n"+
	" org.objectweb.fractal.adl,\n"+
	" org.objectweb.fractal.adl.arguments,\n"+
	" org.objectweb.fractal.adl.attributes,\n"+
	" org.objectweb.fractal.adl.bindings,\n"+
	" org.objectweb.fractal.adl.comments,\n"+
	" org.objectweb.fractal.adl.components,\n"+
	" org.objectweb.fractal.adl.coordinates,\n"+
	" org.objectweb.fractal.adl.implementations,\n"+
	" org.objectweb.fractal.adl.interfaces,\n"+
	" org.objectweb.fractal.adl.loggers,\n"+
	" org.objectweb.fractal.adl.nodes,\n"+
	" org.objectweb.fractal.adl.types,\n"+
	" org.objectweb.fractal.adl.util,\n"+
	" org.objectweb.fractal.adl.xml,\n"+
	" org.objectweb.fractal.api,\n"+
	" org.objectweb.fractal.api.control,\n"+
	" org.objectweb.fractal.api.factory,\n"+
	" org.objectweb.fractal.api.type,\n"+
	" org.objectweb.fractal.julia,\n"+
	" org.objectweb.fractal.julia.ant,\n"+
	" org.objectweb.fractal.julia.asm,\n"+
	" org.objectweb.fractal.julia.control.attribute,\n"+
	" org.objectweb.fractal.julia.control.binding,\n"+
	" org.objectweb.fractal.julia.control.content,\n"+
	" org.objectweb.fractal.julia.control.lifecycle,\n"+
	" org.objectweb.fractal.julia.control.name,\n"+
	" org.objectweb.fractal.julia.factory,\n"+
	" org.objectweb.fractal.julia.loader,\n"+
	" org.objectweb.fractal.julia.logger,\n"+
	" org.objectweb.fractal.julia.type,\n"+
	" org.objectweb.fractal.util,\n"+
	" org.objectweb.proactive,\n"+
	" org.objectweb.proactive.annotation,\n"+
	" org.objectweb.proactive.api,\n"+
	" org.objectweb.proactive.benchmarks.timit,\n"+
	" org.objectweb.proactive.benchmarks.timit.config,\n"+
	" org.objectweb.proactive.benchmarks.timit.pics,\n"+
	" org.objectweb.proactive.benchmarks.timit.result,\n"+
	" org.objectweb.proactive.benchmarks.timit.util,\n"+
	" org.objectweb.proactive.benchmarks.timit.util.basic,\n"+
	" org.objectweb.proactive.benchmarks.timit.util.charts,\n"+
	" org.objectweb.proactive.benchmarks.timit.util.charts.renderer,\n"+
	" org.objectweb.proactive.benchmarks.timit.util.observing,\n"+
	" org.objectweb.proactive.benchmarks.timit.util.observing.commobserv,\n"+
	" org.objectweb.proactive.benchmarks.timit.util.observing.defaultobserver,\n"+
	" org.objectweb.proactive.benchmarks.timit.util.service,\n"+
	" org.objectweb.proactive.core,\n"+
	" org.objectweb.proactive.core.body,\n"+
	" org.objectweb.proactive.core.body.exceptions,\n"+
	" org.objectweb.proactive.core.body.ft.checkpointing,\n"+
	" org.objectweb.proactive.core.body.ft.exception,\n"+
	" org.objectweb.proactive.core.body.ft.internalmsg,\n"+
	" org.objectweb.proactive.core.body.ft.message,\n"+
	" org.objectweb.proactive.core.body.ft.protocols,\n"+
	" org.objectweb.proactive.core.body.ft.protocols.cic.infos,\n"+
	" org.objectweb.proactive.core.body.ft.protocols.cic.managers,\n"+
	" org.objectweb.proactive.core.body.ft.protocols.cic.servers,\n"+
	" org.objectweb.proactive.core.body.ft.protocols.pmlrb.infos,\n"+
	" org.objectweb.proactive.core.body.ft.protocols.pmlrb.managers,\n"+
	" org.objectweb.proactive.core.body.ft.protocols.pmlrb.servers,\n"+
	" org.objectweb.proactive.core.body.ft.servers,\n"+
	" org.objectweb.proactive.core.body.ft.servers.faultdetection,\n"+
	" org.objectweb.proactive.core.body.ft.servers.location,\n"+
	" org.objectweb.proactive.core.body.ft.servers.recovery,\n"+
	" org.objectweb.proactive.core.body.ft.servers.resource,\n"+
	" org.objectweb.proactive.core.body.ft.servers.storage,\n"+
	" org.objectweb.proactive.core.body.ft.servers.util,\n"+
	" org.objectweb.proactive.core.body.future,\n"+
	" org.objectweb.proactive.core.body.http,\n"+
	" org.objectweb.proactive.core.body.ibis,\n"+
	" org.objectweb.proactive.core.body.message,\n"+
	" org.objectweb.proactive.core.body.migration,\n"+
	" org.objectweb.proactive.core.body.proxy,\n"+
	" org.objectweb.proactive.core.body.reply,\n"+
	" org.objectweb.proactive.core.body.request,\n"+
	" org.objectweb.proactive.core.body.rmi,\n"+
	" org.objectweb.proactive.core.classloader,\n"+
	" org.objectweb.proactive.core.component,\n"+
	" org.objectweb.proactive.core.component.adl,\n"+
	" org.objectweb.proactive.core.component.adl.bindings,\n"+
	" org.objectweb.proactive.core.component.adl.components,\n"+
	" org.objectweb.proactive.core.component.adl.implementations,\n"+
	" org.objectweb.proactive.core.component.adl.nodes,\n"+
	" org.objectweb.proactive.core.component.adl.types,\n"+
	" org.objectweb.proactive.core.component.adl.vnexportation,\n"+
	" org.objectweb.proactive.core.component.adl.xml,\n"+
	" org.objectweb.proactive.core.component.body,\n"+
	" org.objectweb.proactive.core.component.collectiveitfs,\n"+
	" org.objectweb.proactive.core.component.config,\n"+
	" org.objectweb.proactive.core.component.controller,\n"+
	" org.objectweb.proactive.core.component.exceptions,\n"+
	" org.objectweb.proactive.core.component.factory,\n"+
	" org.objectweb.proactive.core.component.gen,\n"+
	" org.objectweb.proactive.core.component.group,\n"+
	" org.objectweb.proactive.core.component.identity,\n"+
	" org.objectweb.proactive.core.component.interception,\n"+
	" org.objectweb.proactive.core.component.representative,\n"+
	" org.objectweb.proactive.core.component.request,\n"+
	" org.objectweb.proactive.core.component.type,\n"+
	" org.objectweb.proactive.core.component.type.annotations.gathercast,\n"+
	" org.objectweb.proactive.core.component.type.annotations.multicast,\n"+
	" org.objectweb.proactive.core.config,\n"+
	" org.objectweb.proactive.core.config.xml,\n"+
	" org.objectweb.proactive.core.descriptor,\n"+
	" org.objectweb.proactive.core.descriptor.data,\n"+
	" org.objectweb.proactive.core.descriptor.legacyparser,\n"+
	" org.objectweb.proactive.core.descriptor.parser,\n"+
	" org.objectweb.proactive.core.descriptor.services,\n"+
	" org.objectweb.proactive.core.descriptor.util,\n"+
	" org.objectweb.proactive.core.descriptor.xml.schemas.deployment,\n"+
	" org.objectweb.proactive.core.descriptor.xml.schemas.security,\n"+
	" org.objectweb.proactive.core.event,\n"+
	" org.objectweb.proactive.core.exceptions,\n"+
	" org.objectweb.proactive.core.filetransfer,\n"+
	" org.objectweb.proactive.core.filter,\n"+
	" org.objectweb.proactive.core.gc,\n"+
	" org.objectweb.proactive.core.group,\n"+
	" org.objectweb.proactive.core.group.spmd,\n"+
	" org.objectweb.proactive.core.group.threadpool,\n"+
	" org.objectweb.proactive.core.group.topology,\n"+
	" org.objectweb.proactive.core.jmx,\n"+
	" org.objectweb.proactive.core.jmx.client,\n"+
	" org.objectweb.proactive.core.jmx.listeners,\n"+
	" org.objectweb.proactive.core.jmx.mbean,\n"+
	" org.objectweb.proactive.core.jmx.naming,\n"+
	" org.objectweb.proactive.core.jmx.notification,\n"+
	" org.objectweb.proactive.core.jmx.provider.proactive,\n"+
	" org.objectweb.proactive.core.jmx.server,\n"+
	" org.objectweb.proactive.core.jmx.util,\n"+
	" org.objectweb.proactive.core.migration,\n"+
	" org.objectweb.proactive.core.mop,\n"+
	" org.objectweb.proactive.core.node,\n"+
	" org.objectweb.proactive.core.process,\n"+
	" org.objectweb.proactive.core.process.filetransfer,\n"+
	" org.objectweb.proactive.core.process.glite,\n"+
	" org.objectweb.proactive.core.process.globus,\n"+
	" org.objectweb.proactive.core.process.gridengine,\n"+
	" org.objectweb.proactive.core.process.loadleveler,\n"+
	" org.objectweb.proactive.core.process.lsf,\n"+
	" org.objectweb.proactive.core.process.mpi,\n"+
	" org.objectweb.proactive.core.process.nordugrid,\n"+
	" org.objectweb.proactive.core.process.oar,\n"+
	" org.objectweb.proactive.core.process.pbs,\n"+
	" org.objectweb.proactive.core.process.prun,\n"+
	" org.objectweb.proactive.core.process.rlogin,\n"+
	" org.objectweb.proactive.core.process.rocks,\n"+
	" org.objectweb.proactive.core.process.rsh,\n"+
	" org.objectweb.proactive.core.process.rsh.maprsh,\n"+
	" org.objectweb.proactive.core.process.ssh,\n"+
	" org.objectweb.proactive.core.process.unicore,\n"+
	" org.objectweb.proactive.core.remoteobject,\n"+
	" org.objectweb.proactive.core.remoteobject.adapter,\n"+
	" org.objectweb.proactive.core.remoteobject.exception,\n"+
	" org.objectweb.proactive.core.remoteobject.http,\n"+
	" org.objectweb.proactive.core.remoteobject.http.message,\n"+
	" org.objectweb.proactive.core.remoteobject.http.util,\n"+
	" org.objectweb.proactive.core.remoteobject.http.util.exceptions,\n"+
	" org.objectweb.proactive.core.remoteobject.http.util.messages,\n"+
	" org.objectweb.proactive.core.remoteobject.ibis,\n"+
	" org.objectweb.proactive.core.remoteobject.rmi,\n"+
	" org.objectweb.proactive.core.remoteobject.rmissh,\n"+
	" org.objectweb.proactive.core.rmi,\n"+
	" org.objectweb.proactive.core.runtime,\n"+
	" org.objectweb.proactive.core.security,\n"+
	" org.objectweb.proactive.core.security.crypto,\n"+
	" org.objectweb.proactive.core.security.domain,\n"+
	" org.objectweb.proactive.core.security.exceptions,\n"+
	" org.objectweb.proactive.core.security.securityentity,\n"+
	" org.objectweb.proactive.core.security.test.jacobi,\n"+
	" org.objectweb.proactive.core.ssh,\n"+
	" org.objectweb.proactive.core.ssh.httpssh,\n"+
	" org.objectweb.proactive.core.ssh.rmissh,\n"+
	" org.objectweb.proactive.core.util,\n"+
	" org.objectweb.proactive.core.util.converter,\n"+
	" org.objectweb.proactive.core.util.log,\n"+
	" org.objectweb.proactive.core.util.profiling,\n"+
	" org.objectweb.proactive.core.util.wrapper,\n"+
	" org.objectweb.proactive.core.xml,\n"+
	" org.objectweb.proactive.core.xml.handler,\n"+
	" org.objectweb.proactive.core.xml.io,\n"+
	" org.objectweb.proactive.ext.locationserver,\n"+
	" org.objectweb.proactive.ext.util,\n"+
	" org.objectweb.proactive.extensions.branchnbound,\n"+
	" org.objectweb.proactive.extensions.branchnbound.core,\n"+
	" org.objectweb.proactive.extensions.branchnbound.core.exception,\n"+
	" org.objectweb.proactive.extensions.branchnbound.core.queue,\n"+
	" org.objectweb.proactive.extensions.calcium,\n"+
	" org.objectweb.proactive.extensions.calcium.diagnosis,\n"+
	" org.objectweb.proactive.extensions.calcium.diagnosis.causes,\n"+
	" org.objectweb.proactive.extensions.calcium.diagnosis.inferences,\n"+
	" org.objectweb.proactive.extensions.calcium.environment,\n"+
	" org.objectweb.proactive.extensions.calcium.environment.multithreaded,\n"+
	" org.objectweb.proactive.extensions.calcium.environment.proactive,\n"+
	" org.objectweb.proactive.extensions.calcium.examples,\n"+
	" org.objectweb.proactive.extensions.calcium.examples.blast,\n"+
	" org.objectweb.proactive.extensions.calcium.examples.findprimes,\n"+
	" org.objectweb.proactive.extensions.calcium.examples.nqueens,\n"+
	" org.objectweb.proactive.extensions.calcium.examples.nqueens.bt1,\n"+
	" org.objectweb.proactive.extensions.calcium.examples.nqueens.bt2,\n"+
	" org.objectweb.proactive.extensions.calcium.exceptions,\n"+
	" org.objectweb.proactive.extensions.calcium.futures,\n"+
	" org.objectweb.proactive.extensions.calcium.instructions,\n"+
	" org.objectweb.proactive.extensions.calcium.monitor,\n"+
	" org.objectweb.proactive.extensions.calcium.muscle,\n"+
	" org.objectweb.proactive.extensions.calcium.skeletons,\n"+
	" org.objectweb.proactive.extensions.calcium.stateness,\n"+
	" org.objectweb.proactive.extensions.calcium.statistics,\n"+
	" org.objectweb.proactive.extensions.calcium.system,\n"+
	" org.objectweb.proactive.extensions.calcium.system.files,\n"+
	" org.objectweb.proactive.extensions.calcium.task,\n"+
	" org.objectweb.proactive.extensions.jmx,\n"+
	" org.objectweb.proactive.extensions.masterworker,\n"+
	" org.objectweb.proactive.extensions.masterworker.core,\n"+
	" org.objectweb.proactive.extensions.masterworker.interfaces,\n"+
	" org.objectweb.proactive.extensions.masterworker.interfaces.internal,\n"+
	" org.objectweb.proactive.extensions.masterworker.tasks,\n"+
	" org.objectweb.proactive.extensions.masterworker.util,\n"+
	" org.objectweb.proactive.extensions.mixedlocation,\n"+
	" org.objectweb.proactive.extensions.osgi,\n"+
	" org.objectweb.proactive.extensions.osgi.Manifest,\n"+
	" org.objectweb.proactive.extensions.osgi.connector,\n"+
	" org.objectweb.proactive.extensions.osgi.connector.Manifest,\n"+
	" org.objectweb.proactive.extensions.osgi.res,\n"+
	" org.objectweb.proactive.extensions.resourcemanager,\n"+
	" org.objectweb.proactive.extensions.resourcemanager.common,\n"+
	" org.objectweb.proactive.extensions.resourcemanager.common.event,\n"+
	" org.objectweb.proactive.extensions.resourcemanager.core,\n"+
	" org.objectweb.proactive.extensions.resourcemanager.exception,\n"+
	" org.objectweb.proactive.extensions.resourcemanager.frontend,\n"+
	" org.objectweb.proactive.extensions.resourcemanager.nodesource.dynamic,\n"+
	" org.objectweb.proactive.extensions.resourcemanager.nodesource.frontend,\n"+
	" org.objectweb.proactive.extensions.resourcemanager.nodesource.pad,\n"+
	" org.objectweb.proactive.extensions.resourcemanager.rmnode,\n"+
	" org.objectweb.proactive.extensions.resourcemanager.test.simple,\n"+
	" org.objectweb.proactive.extensions.resourcemanager.test.util,\n"+
	" org.objectweb.proactive.extensions.resourcemanager.utils,\n"+
	" org.objectweb.proactive.extensions.scheduler,\n"+
	" org.objectweb.proactive.extensions.scheduler.common.exception,\n"+
	" org.objectweb.proactive.extensions.scheduler.common.job,\n"+
	" org.objectweb.proactive.extensions.scheduler.common.scheduler,\n"+
	" org.objectweb.proactive.extensions.scheduler.common.scripting,\n"+
	" org.objectweb.proactive.extensions.scheduler.common.task,\n"+
	" org.objectweb.proactive.extensions.scheduler.common.task.executable,\n"+
	" org.objectweb.proactive.extensions.scheduler.common.task.util,\n"+
	" org.objectweb.proactive.extensions.scheduler.common.xml.schemas.jobdescriptor,\n"+
	" org.objectweb.proactive.extensions.scheduler.common.xml.stylesheets,\n"+
	" org.objectweb.proactive.extensions.scheduler.core,\n"+
	" org.objectweb.proactive.extensions.scheduler.core.db,\n"+
	" org.objectweb.proactive.extensions.scheduler.examples,\n"+
	" org.objectweb.proactive.extensions.scheduler.exception,\n"+
	" org.objectweb.proactive.extensions.scheduler.ext.matlab,\n"+
	" org.objectweb.proactive.extensions.scheduler.ext.matlab.exception,\n"+
	" org.objectweb.proactive.extensions.scheduler.ext.scilab,\n"+
	" org.objectweb.proactive.extensions.scheduler.ext.scilab.exception,\n"+
	" org.objectweb.proactive.extensions.scheduler.job,\n"+
	" org.objectweb.proactive.extensions.scheduler.policy,\n"+
	" org.objectweb.proactive.extensions.scheduler.resourcemanager,\n"+
	" org.objectweb.proactive.extensions.scheduler.task,\n"+
	" org.objectweb.proactive.extensions.scheduler.task.internal,\n"+
	" org.objectweb.proactive.extensions.scheduler.util,\n"+
	" org.objectweb.proactive.extensions.scheduler.util.logforwarder,\n"+
	" org.objectweb.proactive.extensions.scilab,\n"+
	" org.objectweb.proactive.extensions.scilab.gui,\n"+
	" org.objectweb.proactive.extensions.scilab.gui.img,\n"+
	" org.objectweb.proactive.extensions.scilab.monitor,\n"+
	" org.objectweb.proactive.extensions.scilab.test,\n"+
	" org.objectweb.proactive.extensions.scilab.util,\n"+
	" org.objectweb.proactive.extensions.security.loginmodule,\n"+
	" org.objectweb.proactive.extensions.webservices,\n"+
	" org.objectweb.proactive.extensions.webservices.soap,\n"+
	" org.objectweb.proactive.extensions.webservices.utils,\n"+
	" org.objectweb.proactive.extensions.webservices.wsdl,\n"+
	" org.objectweb.proactive.extra.calcium.environment.proactivescheduler,\n"+
	" org.objectweb.proactive.extra.closedworldlauncher,\n"+
	" org.objectweb.proactive.extensions.gcmdeployment,\n"+
	" org.objectweb.proactive.extensions.gcmdeployment.GCMApplication,\n"+
	" org.objectweb.proactive.extensions.gcmdeployment.GCMApplication.ApplicationParsers,\n"+
	" org.objectweb.proactive.extensions.gcmdeployment.GCMDeployment,\n"+
	" org.objectweb.proactive.extensions.gcmdeployment.GCMDeployment.BridgeParsers,\n"+
	" org.objectweb.proactive.extensions.gcmdeployment.GCMDeployment.BridgeSchemas,\n"+
	" org.objectweb.proactive.extensions.gcmdeployment.GCMDeployment.GroupParsers,\n"+
	" org.objectweb.proactive.extensions.gcmdeployment.GCMDeployment.GroupSchemas,\n"+
	" org.objectweb.proactive.extensions.gcmdeployment.core,\n"+
	" org.objectweb.proactive.extensions.gcmdeployment.environment,\n"+
	" org.objectweb.proactive.extensions.gcmdeployment.process,\n"+
	" org.objectweb.proactive.extensions.gcmdeployment.process.bridge,\n"+
	" org.objectweb.proactive.extensions.gcmdeployment.process.commandbuilder,\n"+
	" org.objectweb.proactive.extensions.gcmdeployment.process.group,\n"+
	" org.objectweb.proactive.extensions.gcmdeployment.process.hostinfo,\n"+
	" org.objectweb.proactive.extensions.gcmdeployment.schema,\n"+
	" org.objectweb.proactive.extensions.gcmdeployment.specifications,\n"+
	" org.objectweb.proactive.extra.p2pTest.scripts,\n"+
	" org.objectweb.proactive.extra.security.xacml,\n"+
	" org.objectweb.proactive.loadbalancing,\n"+
	" org.objectweb.proactive.loadbalancing.metrics,\n"+
	" org.objectweb.proactive.loadbalancing.metrics.CPURanking,\n"+
	" org.objectweb.proactive.loadbalancing.metrics.currenttimemillis,\n"+
	" org.objectweb.proactive.loadbalancing.util,\n"+
	" org.objectweb.proactive.mpi,\n"+
	" org.objectweb.proactive.mpi.control,\n"+
	" org.objectweb.proactive.mpi.control.util,\n"+
	" org.objectweb.proactive.p2p.daemon,\n"+
	" org.objectweb.proactive.p2p.loadbalancer,\n"+
	" org.objectweb.proactive.p2p.service,\n"+
	" org.objectweb.proactive.p2p.service.exception,\n"+
	" org.objectweb.proactive.p2p.service.node,\n"+
	" org.objectweb.proactive.p2p.service.util,\n"+
	" org.objectweb.proactive.p2p.v2.dynamicnoa,\n"+
	" org.objectweb.proactive.p2p.v2.monitoring,\n"+
	" org.objectweb.proactive.p2p.v2.monitoring.event,\n"+
	" org.objectweb.proactive.p2p.v2.service,\n"+
	" org.objectweb.proactive.p2p.v2.service.exception,\n"+
	" org.objectweb.proactive.p2p.v2.service.messages,\n"+
	" org.objectweb.proactive.p2p.v2.service.node,\n"+
	" org.objectweb.proactive.p2p.v2.service.util,\n"+
	" org.osgi.framework,\n"+
	" org.osgi.service.http,\n"+
	" org.osgi.service.packageadmin,\n"+
	" org.osgi.service.startlevel,\n"+
	" org.relaxng.datatype,\n"+
	" org.relaxng.datatype.helpers,\n"+
	" org.soapinterop,\n"+
	" org.ungoverned.gravity.servicebinder,\n"+
	" org.ungoverned.gravity.servicebinder.architecture,\n"+
	" org.ungoverned.gravity.servicebinder.impl,\n"+
	" org.ungoverned.gravity.servicebinder.parser,\n"+
	" org.ungoverned.moduleloader,\n"+
	" org.ungoverned.moduleloader.search,\n"+
	" org.ungoverned.moduleloader.search.compatibility,\n"+
	" org.ungoverned.moduleloader.search.selection,\n"+
	" org.ungoverned.oscar,\n"+
	" org.ungoverned.oscar.ldap,\n"+
	" org.ungoverned.oscar.util,\n"+
	" org.ungoverned.osgi.bundle.bundlerepository,\n"+
	" org.ungoverned.osgi.bundle.http,\n"+
	" org.ungoverned.osgi.bundle.shell,\n"+
	" org.ungoverned.osgi.bundle.shellgui,\n"+
	" org.ungoverned.osgi.bundle.shellgui.impl,\n"+
	" org.ungoverned.osgi.bundle.shellplugin,\n"+
	" org.ungoverned.osgi.bundle.shelltui,\n"+
	" org.ungoverned.osgi.bundle.simple,\n"+
	" org.ungoverned.osgi.service.bundlerepository,\n"+
	" org.ungoverned.osgi.service.shell,\n"+
	" org.unicore,\n"+
	" org.unicore.ajo,\n"+
	" org.unicore.idiomatic,\n"+
	" org.unicore.outcome,\n"+
	" org.unicore.resources,\n"+
	" org.unicore.sets,\n"+
	" org.unicore.upl,\n"+
	" org.unicore.utility,\n"+
	" org.w3c.dom,\n"+
	" org.w3c.dom.bootstrap,\n"+
	" org.w3c.dom.css,\n"+
	" org.w3c.dom.events,\n"+
	" org.w3c.dom.html,\n"+
	" org.w3c.dom.ls,\n"+
	" org.w3c.dom.ranges,\n"+
	" org.w3c.dom.stylesheets,\n"+
	" org.w3c.dom.traversal,\n"+
	" org.w3c.dom.views,\n"+
	" org.w3c.dom.xpath,\n"+
	" org.xml.sax,\n"+
	" org.xml.sax.ext,\n"+
	" org.xml.sax.helpers,\n"+
	" pa.stub.org.objectweb.proactive.core.body,\n"+
	" pa.stub.org.objectweb.proactive.core.runtime,\n"+
	" pa.stub.org.objectweb.proactive.core.util.wrapper,\n"+
	" pa.stub.org.objectweb.proactive.extensions.calcium.environment.proactive,\n"+
	" pa.stub.org.objectweb.proactive.extensions.calcium.task,\n"+
	" pa.stub.org.objectweb.proactive.extensions.masterworker,\n"+
	" pa.stub.org.objectweb.proactive.extensions.masterworker.core,\n"+
	" pa.stub.org.objectweb.proactive.extensions.masterworker.interfaces,\n"+
	" pa.stub.org.objectweb.proactive.extensions.masterworker.interfaces.internal,\n"+
	" pa.stub.org.objectweb.proactive.extensions.masterworker.tasks,\n"+
	" pa.stub.org.objectweb.proactive.extensions.masterworker.util,\n"+
	" propertyTest,\n"+
	" ptolemy.data,\n"+
	" ptolemy.data.expr,\n"+
	" ptolemy.data.type,\n"+
	" ptolemy.data.unit,\n"+
	" ptolemy.graph,\n"+
	" ptolemy.graph.analysis,\n"+
	" ptolemy.graph.analysis.analyzer,\n"+
	" ptolemy.graph.analysis.strategy,\n"+
	" ptolemy.graph.mapping,\n"+
	" ptolemy.kernel,\n"+
	" ptolemy.kernel.attributes,\n"+
	" ptolemy.kernel.util,\n"+
	" ptolemy.math,\n"+
	" ptolemy.matlab,\n"+
	" ptolemy.matlab.test,\n"+
	" ptolemy.util,\n"+
	" samples.graph,\n"+
	" samples.graph.southern,\n"+
	" samples.preview_new_graphdraw,\n"+
	" samples.preview_new_graphdraw.event,\n"+
	" samples.preview_new_graphdraw.impl,\n"+
	" samples.preview_new_graphdraw.impl.crooked,\n"+
	" samples.preview_new_graphdraw.iter,\n"+
	" samples.preview_new_graphdraw.iterablelayouts,\n"+
	" samples.preview_new_graphdraw.staticlayouts,\n"+
	" samples.preview_new_graphdraw.test,\n"+
	" samples.preview_new_graphdraw.transform,\n"+
	" sources,\n"+
	" text,\n"+
	" text.ftp,\n"+
	" text.setup,\n"+
	" timer,\n"+
	" trywithcatch,\n"+
	" trywithcatch.java_cup.runtime,\n"+
	" xjava.lang,\n"+
	" xjava.security,\n"+
	" xjava.security.interfaces";
}
