#! /bin/bash

for i in $NODES ; 
do
	if [ "$CLUSTER" != "`get_cluster_from_hostname $i`" ] ; then
		continue # $i does not belong to $CLUSTER
	fi

	KADEPLOY_ARGS="$KADEPLOY_ARGS -m $i "	
done

ssh $(get_oar_hostname $CLUSTER) kadeploy $KADEPLOY_ARGS

# TODO: Check that kadeploy succeded.
#       Unfortunately it seems that kadeploy's devels only know 0 as exit status... 


SSH=$(dirname $0)/deploy/ssh_autologin.exp

for i in $NODES ; 
do
	if [ "$CLUSTER" != "`get_cluster_from_hostname $i`" ] ; then
		if [ "$Verbose" = "Yes" ] ; then
			echo "Skip $i's configuration since it does not belong to $CLUSTER" 1>&2
		fi
		continue
	fi

	# WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!
	# PLEASE SHUT UP !
	#sed -i "s/^$i.*//"  ~/.ssh/known_hosts
	rm  ~/.ssh/known_hosts

	$SSH $ROOT_PASSWD $i  mkdir /home /home/sophia 
	$SSH $ROOT_PASSWD $i  mount -t nfs -o rsize=1024,wsize=1024  $MOUNT_ARGS
	
	$SSH $ROOT_PASSWD $i groupadd  -g `id -g` sophia 
	$SSH $ROOT_PASSWD $i useradd -d $HOME -g `id -g` -p grid5000 -u `id -u` $USER
	$SSH $ROOT_PASSWD $i  echo AllowUsers root $USER \>\> /etc/ssh/sshd_config 
	$SSH $ROOT_PASSWD $i  /etc/init.d/ssh reload
	$SSH $ROOT_PASSWD $i  /etc/init.d/sshd reload

	# Disable haldaemon on helios to avoid system load
	if [ "$CLUSTER" = "helios.sophia" ] ; then
		$SSH $ROOT_PASSWD $i  /etc/init.d/haldaemon stop
	fi
		
done

echo "Hint: g5k_reservedNodes -c can be used to retrieve the list of working nodes"

